### ISSUE TITLE
How to use with Class components?

### ISSUE THREAD

**Issue by andrewluetgers** [dai-shi/react-tracked#10]
Is this limited to usage with functional components? I would like to integrate into an existing project that uses class components. Any examples of this?

**Comment by dai-shi** [comment]
React hooks only works in function components.
If you would like to use class components, you would need to wrap your class components with function components.

I created an example. Hope it helps.
https://codesandbox.io/s/react-tracked-example-n3hkl

**Comment by andrewluetgers** [comment]
ahh I see, thanks so much!!

**Comment by dai-shi** [comment]
You are welcome!

**Comment by kaushalshahActonate** [comment]
@dai-shi @andrewluetgers 
### I have listed a two way through which context can be used in Class components
1. **Render Props Patterm**
2. **HOC Pattern**


**Render Props Patterm**
1. (Same as Consumer of React Context)

  ```
const Consumer = (props: {children: ([state, dispatch]: [S, React.Dispatch<A>]) => JSX.Element;}) => {
    const [state, dispatch] = useTracked();
    return props.children([state, dispatch]);
  };
```

Usage
```
      <UserContextConsumer>
        {([state, dispatch]) => {
           return(<></>)
         }}
      </UserContextConsumer>
```

 **HOC  Patterm**
1. wrap class with HOC
2.  access context through props;

  ```
 const WithTracked = (Component: ComponentType) => (props: any) => {
    const [state, dispatch] = useTracked();
    return <Component state={state} dispatch={dispatch} {...props} />;
  };
```

Usage

   ```
   class ClassComponent extends React.Component<{}, {}> {
         render() {
        const { state, dispatch } = this.props;
        return <></>
         }
     }
   export const WrappedClassComponent  = WithTracked(ClassComponent );

```

**Comment by kaushalshah98** [comment]
@dai-shi @andrewluetgers 
### I have listed a two way through which context can be used in Class components
1. **Render Props Patterm**
2. **HOC Pattern**


**Render Props Patterm**
1. (Same as Consumer of React Context)

  ```
const Consumer = (props: {children: ([state, dispatch]: [S, React.Dispatch<A>]) => JSX.Element;}) => {
    const [state, dispatch] = useTracked();
    return props.children([state, dispatch]);
  };
```

Usage
```
      <UserContextConsumer>
        {([state, dispatch]) => {
           return(<></>)
         }}
      </UserContextConsumer>
```

 **HOC  Patterm**
1. wrap class with HOC
2.  access context through props;

  ```
 const WithTracked = (Component: ComponentType) => (props: any) => {
    const [state, dispatch] = useTracked();
    return <Component state={state} dispatch={dispatch} {...props} />;
  };
```

Usage

   ```
   class ClassComponent extends React.Component<{}, {}> {
         render() {
        const { state, dispatch } = this.props;
        return <></>
         }
     }
   export const WrappedClassComponent  = WithTracked(ClassComponent );

```
