### ISSUE TITLE
Why isn't react-tracked more popular?

### ISSUE THREAD

**Issue by ramiAbdou** [dai-shi/react-tracked#105]
Looks like this is such a solid library, and the creators of `react-tracked` are very well known. It just scares me that there's only 7K weekly downloads on NPM.

Why isn't this library the golden standard as an alternative to just React Context API?

**Comment by dai-shi** [comment]
The popularity is just hard...

For me, valtio seems more popular than react-tracked.

https://www.npmtrends.com/constate-vs-react-tracked-vs-valtio-vs-zustand-vs-reactive-react-redux

<img width="969" alt="image" src="https://user-images.githubusercontent.com/490574/123561965-a116ad80-d7e6-11eb-8f1a-c7a513c5af89.png">
<img width="971" alt="image" src="https://user-images.githubusercontent.com/490574/123561972-a7a52500-d7e6-11eb-895f-b9f4d904b5a1.png">

**Comment by rimsila** [comment]
@dai-shi  I love react-tracked, but I have one comment and suggestion for react-tracked,  if we can use it as normal custom hook then it will more easy to use, clean code and no learning cost. thanks you

I found a library under Alibaba team using normal custom hook then convert it to context with build-in selector https://github.com/umijs/hox (seem not maintain)

Ex: if react-tracked can do like it more easy to use

```tsx
import { useState } from "react";
import useSWR from 'swr';
import { createStore } from "react-tracked";

function useCounter() {
  const [count, setCount] = useState(0);
  const decrement = () => setCount(count - 1);
  const increment = () => setCount(count + 1);
   const { data, error } = useSWR('/api/user', fetcher)
   
  return {
   data,
    error,
    count,
    decrement,
    increment
  };
}

export default createStore(useCounter);
```

### usage in component
```tsx
import useCounterStore from "../store/counter";

function App(props) {
  const count = useCounterStore(model => [model.count,model, increment]);
  return (
    <div>
      <p>{counter.count}</p>
      <button onClick={counter.increment}>Increment</button>
    </div>
  );
}


```

**Comment by dai-shi** [comment]
Thanks for the feedback. Unfortunately, react-tracked requires the second item in the tuple to be a function. This is to better fit with concurrent rendering. And, Provider is a requirement for the same reason.

```jsx
import { useState } from "react";
import useSWR from 'swr';
import { createContainer } from "react-tracked";

function useCounter() {
  const [count, setCount] = useState(0);
  const decrement = () => setCount(count - 1);
  const increment = () => setCount(count + 1);
  const { data, error } = useSWR('/api/user', fetcher);
   
  return [{
    data,
    error,
    count,
  }, (action) => {
    switch (action.type) {
      case 'decrement':
        decrement();
        break;
      case 'increment':
        increment();
    }
  }];
};

const {
  Provider,
  useUpdate as useDispatch,
  useSelector
} = createContainer(useCounter);

export const useCounterStore = (selector) => {
  return [useSelector(selector), useDispath()];
};

export { Provider };
```

This works the closest to your example.

---
By the way:
If what you want is a module state rather than react context, I'd suggest to try [zustand](https://github.com/pmndrs/zustand).
If you don't need `useTrackedState`, then you might like [jotai](https://github.com/pmndrs/jotai) too.
If you like `useTrackedState`, another option is [valtio](https://github.com/pmndrs/valtio).
react-tracked is mainly for adding "state usage tracking" to React Context.

---
Ah, I found your past question: #65

**Comment by dai-shi** [comment]
Closing as stale.
