### ISSUE TITLE
can't debug context with chrome devtools

### ISSUE THREAD

**Issue by talwaserman** [dai-shi/react-tracked#107]
Hello,
When using this library i can't see the context in chrome dev-tools
is there any solution for this?

**Comment by dai-shi** [comment]
It's using [use-context-selector](https://github.com/dai-shi/use-context-selector) underneath, which put a special ref in a context in the current version.
I'm not sure if there's any workaround, unfortunately...

**Comment by talwaserman** [comment]
So correct me if i'm wrong, i will not be able to view my context parameters in any way with the chrome-dev tools or by any other plugin?
i think this library and your work is great and it solved me the render problem i had but not being able to view context params is something that is important to me

**Comment by dai-shi** [comment]
Well, you are probably making a good point.
Does it help if you can see the value in `useTrackedState` in the devtool?
(`useSelector` has `useDebugValue` in it, and doing the same for `useTrackedState` is trivial.)

**Comment by dai-shi** [comment]
Or, you can do this on your end.
```js
const useValue = () => {
  const [state, setState] = useState();
  useDebugValue(state);
  return [state, setState];
};

export const { ... } = createContainer(useValue);
```

**Comment by talwaserman** [comment]
i'm using useReducer in my context
can you advice what i can change for that code?

```
import React, { useReducer } from 'react';
import { createContainer } from 'react-tracked';
import ChildAReducer from './ChildAReducer';
import ChildBReducer from './ChildBReducer';

const initialState = {
  todoList: ['buy dinner', 'run 5 km', 'finish work'],
  text: '',
  footer: 'footer text'
};

const pageReducer = (state, action) => {
  const combinedReducer = {
    ...ChildAReducer,
    ...ChildBReducer
  };
  return combinedReducer[action.type](state, action);
};

const useValue = () => useReducer(pageReducer, initialState);

const {
  Provider: PageContextProvider,
  useTrackedState,
  useUpdate: useDispatch
} = createContainer(useValue);

export { PageContextProvider, useTrackedState, useDispatch };

```

**Comment by dai-shi** [comment]
Sure, please try this:

```js
const useValue = () => {
  const [state, dispatch] = useReducer(pageReducer, initialState);
  useDebugValue(state);
  return [state, dispatch];
};
```

**Comment by talwaserman** [comment]
Thank you for the fast response,
after more investigation, for the parent container adding useDebugValue is not needed
since i can actually see it when standing on Provider DOM element, you can see in image1 on the right the reducer is visible

and for nester components in image2 when i drill down on the right i can find the context key that is used by that component, which is cool. so i can work with that

I have 2 questions
1. to find the value that the nested component is using, requires drill down of anonymous functions, as you can see in image2 on the right, is there any way to improve this?

2. in image2 i see that we have 3 refs, two of them show the entire context and get updated when the context changes, why do we have these refs in that location? is that part of the algorithm? 

thanks for the help

Image1
![Screen Shot 2021-07-01 at 10 09 28](https://user-images.githubusercontent.com/4783250/124081672-82b5e980-da54-11eb-8024-7bf51f28bf3d.png)



Image2
![Screen Shot 2021-07-01 at 10 06 30](https://user-images.githubusercontent.com/4783250/124081308-0a4f2880-da54-11eb-9196-686e1646dae1.png)

**Comment by dai-shi** [comment]
image1 looks just fine. so we didn't need the useDebugValue there.

image2 is, as you implied, looking into the internal of use-context-selector.

Would you try this? if it works fine, I can modify the library likewise.

```js
import { createContainer, getUntrackedObject } from 'react-tracked';

// ...

const {
  Provider: PageContextProvider,
  useTrackedState: useTrackedStateOrig,
  useUpdate: useDispatch
} = createContainer(useValue);

const useTrackedState = () => {
  const state = useTrackedStateOrig();
  useDebugValue(state, getUntrackedObject);
  return state;
};

export { PageContextProvider, useTrackedState, useDispatch };
```

**Comment by talwaserman** [comment]
after checking your suggested change
it seems like a good direction for prop readability

but the tracked keys are still under several layers as you can see in the image i added
if it could be like this for example it would be better

```
hooks: {
  TrackedState: {
    DebugValue: {...},
    TrackedKeys: {
      DebugValue: {...},
      Ref: {...}
    }
  }
}
```



image:

![Screen Shot 2021-07-01 at 12 20 32](https://user-images.githubusercontent.com/4783250/124100079-d0d3e880-da66-11eb-8402-5c98e20ffab4.png)

**Comment by dai-shi** [comment]
Oh, yeah, `AffectedValue` was for that. It's shown as Anonymous.
It used to be working. Maybe v1.6.0 broke it.

> image2 is, as you implied, looking into the internal of use-context-selector.

So, this comment was not correct. it's just in createTrackedSelector.

It requires some time to investigate this.
Meanwhile, you may want to try v1.5.1 if it works better.

**Comment by talwaserman** [comment]
Ok, got it
thanks for the clarification
i checked v1.51 looks better without any additional code change, meaning i don't need to change my context file code, just move to that version. 
since i'm afraid to loos all the code updates you made (i was on version 1.7) i wander if it worth downgrading or staying on 1.7 

you can close the issue.
thanks for your help.

**Comment by dai-shi** [comment]
Thanks for confirming.
Downgrading should be temporarily.
Let me try something.

**Comment by dai-shi** [comment]
@talwaserman 
Hi, would you try #108?
See https://ci.codesandbox.io/status/dai-shi/react-tracked/pr/108
and find "Local install instructions".

**Comment by talwaserman** [comment]
sure, will do

**Comment by talwaserman** [comment]
This is how it looks with that change
there are no anonymous functions, but still allot of nested refs and states, i thought it would be more readable
i don't know if it can be achieved


![image](https://user-images.githubusercontent.com/4783250/124125742-a2fc9d00-da82-11eb-8f8f-7244e4e8ba99.png)

**Comment by dai-shi** [comment]
Yeah, I see basically some extra levels.
`TrackedState$1` is because of createContainer, can't be helped.
`TrackedSelector` is because of createTrackedSelector, could be removed if we duplicate code, but may not worth it.
`AffectedDebugValue` can be removed, but then it's hard to know the `Ref` in it shows the "affected" path.

So, unfortunately, it can't be helped much at this point.

Let me merge the PR and cut a release.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-tracked/v/1.7.3

**Comment by talwaserman** [comment]
Thanks
