### ISSUE TITLE
RFC: new API design with breaking changes

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/react-tracked#12]
There's some drawbacks in the current design and I would like to redesign the API.
This is a good moment to get feedback because this is going to be a breaking change.

## Problem 1:
`<Provider useValue={...}>` takes a hook as a prop. This is not very good because props may change. Currently, to mitigate the problem, it warns if useValue is changed between renders.

#### My proposal for problem 1:
We only accept useReduder style state.
`<Provider reducer={...} initialState={...} init={...}>`

## Problem 2:
`createContainer(() => useReducer(...))` doesn't allow receiving initial value from props.

#### My proposal for problem 2:
Make it like `createContainer((props) => ...)`, and accept `props` from `<Provider {...props}>`

----

I would like to hear +1, -1, comments, suggestions, other problems, and so on. Thanks for your contribution!

**Comment by dai-shi** [comment]
#11 previous discussion with @Wildhoney.

**Comment by Wildhoney** [comment]
+1 on Problem 1 for me.

Would call the prop `initialState` rather than `initialArg`.

**Comment by dai-shi** [comment]
> Would call the prop `initialState` rather than `initialArg`.

I wouldn't disagree.
I took the name from https://reactjs.org/docs/hooks-reference.html#usereducer.
But, they use `initialState` in the example code...

OK, let's change it from `initialArg` to `initialState`.

**Comment by kevinya** [comment]
-1 for proposal for problem 1. It does not allow custom hook anymore.

I pushed a pull request #13 that adds an `initialState` prop to Provider.

**Comment by dai-shi** [comment]
Hm, here’s another suggestion. What if we drop defaultContext completely and only provide createContainer? How does that sound?

**Comment by dai-shi** [comment]
More I think about it, better I feel it’s a good primitive.

**Comment by dai-shi** [comment]
If we only provide createContainer, one have to create a custom provider and hooks, but it should be easy as follows. 

```
import { createContainer } from ‘react-tracked’;

export const {
  Provider,
  useTracked,
  // other hooks if needed
} = createContainer(({ reducer, initialState, init }) => useReducer(reducer, initialState, init));
```

**Comment by dai-shi** [comment]
I would like to solve #14 too (without exporting contexts).
