### ISSUE TITLE
React native: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by tommaso-sebastianelli** [dai-shi/react-tracked#122]
I'm creating a RN app and I just switched from standard useStore/Context to react-tracked but I just keep getting this error.

I followed the example for useReduce and I'm using v.1.7.4

store file:

```
const reducerWrapper =
  process.env.NODE_ENV === 'development' ? logger(reducer) : reducer;
const useValue = () => useReducer(reducerWrapper, initialState);

export const {
  Provider: StoreProvider,
  useTrackedState,
  useUpdate: useDispatch,
} = createContainer(useValue);
```

App:

```
const App: React.FC<{}> = () => {
  return (
    <StrictMode>
      <StoreProvider>
        <ThemeProvider theme={theme}>
          <StatusBar barStyle="light-content" />
          <StyledMainView>
            <CharacterList />
          </StyledMainView>
        </ThemeProvider>
      </StoreProvider>
    </StrictMode>
  );
};
```

custom hook where I am using the library:

```
const useApi = () => {
  const dispatch = useDispatch();
  const store = useTrackedState();
  [...]
```
Error:
<img width="1120" alt="Screenshot 2021-09-29 at 18 24 33" src="https://user-images.githubusercontent.com/25106571/135309712-33715e1c-0e12-4cd8-9dee-66f8ca519a3a.png">

Am I missing something?

**Comment by dai-shi** [comment]
Hi, thanks for reporting.
Hm,  the usage seems correct. Can you try to create a reproduction with expo snack?

**Comment by dai-shi** [comment]
Closing as stale.
