### ISSUE TITLE
[question] Testing guide

### ISSUE THREAD

**Issue by drosi94** [dai-shi/react-tracked#123]
Hello!

I did not find a guide on what is the best way to test components that use providers from the react-tracked library.

 I could find a good way to test as I can not mock the value of the state.

Thank you!

**Comment by dai-shi** [comment]
Good point. I usually test both provider and component at once, but you want to test only a component, right? If I were in this situation, I'd probably mock `useTrackedState` from my own `./state.ts`. But, it might not be ideal.
Would you share your thoughts, and how you would do with bare context?
Once we find a good pattern, let's add a guide in the docs.

**Comment by dai-shi** [comment]
Closing as stale.
