### ISSUE TITLE
Error build when using react-tracked with next.js

### ISSUE THREAD

**Issue by DreamEcho100** [dai-shi/react-tracked#126]
I am using [react-tracked](https://react-tracked.js.org/docs/introduction/) as a global store in my next js project and when I am running `npm run build` I get the following error:
```bash
(node:6476) UnhandledPromiseRejectionWarning: file:///E:/GitHub/DreamEcho100/hbo-clone/node_modules/react-tracked/dist/index.modern.mjs:2
import { useContextSelector, useContextUpdate, createContext } from 'use-context-selector';
                                               ^^^^^^^^^^^^^
SyntaxError: Named export 'createContext' not found. The requested module 'use-context-selector' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'use-context-selector';
const { useContextSelector, useContextUpdate, createContext } = pkg;
```

My workaround this is to copy what's in `node_modules/react-tracked/dist/index.modern.mjs` and paste it into a new file in `utils/v1/react-tracked/index.jsx` where I change:

```jsx
// import { useContextSelector, useContextUpdate, createContext } from 'use-context-selector';
import * as pkg from 'use-context-selector';
const { useContextSelector, useContextUpdate, createContext } = pkg;
```

and import [react-tracked](https://react-tracked.js.org/docs/introduction/) from it, and when I run `npm run build` it works.

my question is there no other way to work around this?

I have also posted this in [vercel/next.js/discussions](https://github.com/vercel/next.js/discussions/31354)

**Comment by dai-shi** [comment]
Thanks for reporting!
It's also reported by @grikomsn in Discord, and the PR #125 is filed.

Could you check it quickly?
https://ci.codesandbox.io/status/dai-shi/react-tracked/pr/125
Find "Local Install Instructions" there ☝️

**Comment by DreamEcho100** [comment]
@dai-shi Thanks for your reply I will try it then are if it works.

**Comment by DreamEcho100** [comment]
@dai-shi It works.
I did it after following the link https://ci.codesandbox.io/status/dai-shi/react-tracked/pr/125  `npm i https://pkg.csb.dev/dai-shi/react-tracked/commit/49f9418d/react-tracked`

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-tracked/v/1.7.5
