### ISSUE TITLE
Is it possible to dispatch async actions inside other async actions?

### ISSUE THREAD

**Issue by gabrielhpugliese** [dai-shi/react-tracked#128]
In my example below, I have the first actions that will check if action has correct params and it dispatches the second action that is expected to actually make my API async call.
As far as my debug went, the state changes (isLoadingProject becomes true - because of FETCH_PROJECT_START reducer action) but the second async action never happens. Am I missing something here? What is supposed to happen?

```typescript
const reducer = (state: State, action: Action) => {
  switch (action.type) {
    case ACTION_TYPES.FETCH_PROJECT:
      return state;
    case ACTION_TYPES.FETCH_PROJECT_START:
      return {
        ...state,
        isLoadingProject: true
      };
[...]
};

const asyncActionHandlers = {
  [ACTION_TYPES.FETCH_PROJECT]: ({ dispatch }) => async (
    action: FetchProjectAction
  ) => {
    if (action.projectId == null) {
      return;
    }

    dispatch({
      type: ACTION_TYPES.FETCH_PROJECT_START,
      projectId: action.projectId
    });
  },
  [ACTION_TYPES.FETCH_PROJECT_START]: ({
    dispatch,
    getState,
    signal
  }) => async (action: FetchProjectStartAction) => {
    let project;

    try {
      project = await getProjectById(action.projectId.toString(), signal);
    } catch (error: any) {
      dispatch({ type: ACTION_TYPES.FETCH_PROJECT_FAIL, error });
      return;
    }

    dispatch({ type: ACTION_TYPES.FETCH_PROJECT_SUCCESS, project });
  },
};
```

**Comment by dai-shi** [comment]
You need separate normal pure actions and async actions. For now, we can't dispatch an async action from another async action.
You want to have `ACTION_TYPES.SET_IS_LOADING` or something. Does it make sense? In other words, dispatching an action only triggers either a normal reducer or an action handler.

**Comment by gabrielhpugliese** [comment]
It doesn't make much sense to me. How would I dispatch an action that has an async side-effect if my request fail or is successful? In my example, it's `dispatch({ type: ACTION_TYPES.FETCH_PROJECT_FAIL, error });` or `dispatch({ type: ACTION_TYPES.FETCH_PROJECT_SUCCESS, project });`. I would need to do it from the component, right?

**Comment by gabrielhpugliese** [comment]
Just saw that this was already asked in the correct repo: https://github.com/dai-shi/use-reducer-async/issues/7
But I still don't understand why it's not possible. :) Thanks
