### ISSUE TITLE
Naming Containers for Debugging Purposes

### ISSUE THREAD

**Issue by seanblonien** [dai-shi/react-tracked#130]
I want to be able to distinguish different container context providers by name when using [React DevTools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en).

Unnamed context providers:
![image](https://user-images.githubusercontent.com/33133478/148993582-293ea8b1-5604-4855-8618-6dbd750a0ebb.png)

Even though I know I could just have a single container provider for my whole app (and therefore the naming would not be necessary as it would be clear what the provider is), I currently am migrating from raw-context usage and still have my contexts separated.

All of my contexts do this with the createContainer API:

```tsx
const {Provider, useTrackedState} = createContainer(() => useState({...}));

// derive some custom hooks from useTrackedState...

export {Provider as SpecificSystemProvider};
```

And when I stitch together all of my providers, during runtime, I am unable to distinguish from the different providers I've created (regardless if they are globally scoped or locally scoped), as seen in the screenshot.

`Provider.displayName = 'SpecificSystemProvider';` does not seem to work 😢

The [React Context docs](https://reactjs.org/docs/context.html#contextdisplayname) says you can name the underlying Context object with displayName, so could `createContainer()` have an optional `containerName` parameter that changes the internal `context.displayName` for debugging purposes?

**Comment by dai-shi** [comment]
Oh, nice catch! It was annoying me too.
We actually have two contexts. Do you want to name each?

**Comment by seanblonien** [comment]
Yea that sounds ideal. Well, one thing lead to another and I went ahead and wrote some example code demonstrating an interface option #132 

Considering I don't maintain any open source libraries, I'll leave it up to you how you want to change the `createContainer` interface. I imagine this change should really be minor update in semver version, so I guess adding a third optional argument made sense, although ideally the second argument would just be an object of options, but that would be a breaking change.

**Comment by dai-shi** [comment]
Cool. Assuming that you are not hesitant to contribute to the OSS library, I will add some commits in #132. You can review and test it and then, if it's okay, let's merge it.

**Comment by seanblonien** [comment]
Yea looks good to me, tested these changes with my enterprise app and seems to work as simply as we'd expect it (not much to it really). 

Yes, totally cool with contributing to OSS, I love what you do and the amazing packages you've given to the community ❤

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/react-tracked/v/1.7.6 is published. thanks for your contribution. closing.
