### ISSUE TITLE
[question]: how to optimise renders for derived values

### ISSUE THREAD

**Issue by el-dav** [dai-shi/react-tracked#131]
Hi,

Say I have some tracked state e.g. a counter. Then I have a component `<IsBig />` where the logic is dependant on `count > 5` i.e. true of false.

See this [sandbox](https://codesandbox.io/s/silly-volhard-e0l1i?file=/src/App.js)

Ideally I would only want my component to render when `(count > 5)` changes rather than every time count changes. Is there a simple way to achieve this with react-tracked?

Many thanks for your help!

**Comment by el-dav** [comment]
I've just seen the `useSelector` part of the `createContainer` API which seems to support exactly this as shown in the following [sandbox](https://codesandbox.io/s/youthful-dust-emikg?file=/src/App.js). Thanks again for the great library!

**Comment by dai-shi** [comment]
Exactly! Great you found it out.
