### ISSUE TITLE
Example request: Could you show an example of how to use this library with use-immer?

### ISSUE THREAD

**Issue by nratter** [dai-shi/react-tracked#135]
The immer team also makes a library called 'use-immer' to make it easier to use immer as a react hook. If this library would work well with react-tracked, could you provide an example of how to set up your store using this?

https://github.com/immerjs/use-immer

**Comment by dai-shi** [comment]
It should work!

```js
import { useImmer } from 'use-immer';
import { createContainer } from 'react-tracked';

const useValue = () => useImmer({
  first: 'react',
  last: 'hooks',
});

const {
  Provider,
  useTracked,
  // ...
} = createContainer(useValue);
```

See also our tutorial with bare immer: https://react-tracked.js.org/docs/tutorial-03/
