### ISSUE TITLE
Couldn't reproduce the useReducer recipe from the docs

### ISSUE THREAD

**Issue by theskinnycoder** [dai-shi/react-tracked#141]
By reproduce I mean code was working, but re-rendered the whole component tree, not just the selected property's dependent components. Where am I doing it wrong?

CodeSandBox : https://codesandbox.io/s/cocky-gates-4qeh43

**Comment by dai-shi** [comment]
It looks fine. Do you add `console.log` in render function? Please try wrapping `console.log` in `useEffect`.

**Comment by theskinnycoder** [comment]
> It looks fine. Do you add `console.log` in render function? Please try wrapping `console.log` in `useEffect`.

I linked the code. it has no console logs. in react profiler, when I enabled show rectangles around the components that re rendered, if I change the counter or the text, both of them re render.

**Comment by dai-shi** [comment]
Do you mean this?
<img width="288" alt="image" src="https://user-images.githubusercontent.com/490574/156948129-48947d2c-683b-4f60-966d-c9251f8daea6.png">

When you change the counter, two rectangles are shown, one for Provider and the other for Counter. But, not for InputBox.

This might help?
https://codesandbox.io/s/use-tracked-practice-forked-29pun1
```html
      <div style={{ padding: 50 }}>
```

**Comment by theskinnycoder** [comment]
Oh, man. Yes, I got confused since there was no padding. Thank you for clarifying! So here's my query :

This :

```jsx
const state = useTrackedState();

...

<p>{state?.count}</p>
```

versus this :

```jsx
const { count } = useTrackedState();

...

<p>{count}</p>
```

Would `react-tracked` filter this component from rerendering either way?

**Comment by dai-shi** [comment]
> Would `react-tracked` filter this component from rerendering either way?

Yes, both work.
