### ISSUE TITLE
[question] Is there a way to call useUpdate without a provider?

### ISSUE THREAD

**Issue by totszwai** [dai-shi/react-tracked#142]
I have a component that wish to be optionally wrapped around a react-tracked provider, is there a way to do that?
Right now, if i just call the `useUpdate` hook, it would throw no provider error message. :(

**Comment by dai-shi** [comment]
I haven't thought about the conditional wrapping use case. I could consider covering such use cases, but what you can do on your end is conditionally use `useUpdate` (or other hooks) with wrapping a component (with the same condition). It can be a bit ugly, but maybe no performance downside.

**Comment by totszwai** [comment]
Yeah... but we run **super strict** linter rules here and I can't really throw in a conditional hook. I was thinking maybe there is another way I could do it at the `createContainer` level or whatever it gets returned by the `createContainer` but I'm not sure how. Was hoping that you could give me some pointer in that direction.

The following lint rule won't let me use conditional hooks.
 > "react-hooks/rules-of-hooks": "error",

**Comment by dai-shi** [comment]
> The following lint rule won't let me use conditional hooks.

I don't mean to use conditional hooks, which don't work. I mean conditional components:
```jsx
{condition && <Component />}
```


> maybe there is another way I could do it at the `createContainer` level or whatever it gets returned by the `createContainer`

Hm, hadn't thought about it. Can you provide more explanation of your goal? Some code snippets would help.

**Comment by dai-shi** [comment]
> I wanted to make the `Chart` themselves continue to function with or without provider upstream

What I'm not sure yet is, when you don't have a provider upstream, what should `useUpdate` return?

Another question we may consider is how you would solve it with bare React Context without react-tracked.

**Comment by totszwai** [comment]
Ah you know what, this explains why my code was working before, and with the recent `npm install` which picked up the newer version... my code stopped working.

So before this [commit](https://github.com/dai-shi/react-tracked/commit/a211d93568bbebc5d4cb235f7e49b6a83014290e), I had the following in my code:

```
  const updateLinkChart = useUpdate();
  ...
      if (typeof updateLinkChart === 'function') {
          updateLinkChart({
            chartId: props.id,
            chart: ref.chart
          });
      }
```

So essentially, when `useUpdate` returned null, which what it was actually doing before your fix, it would continue to work regardless of whether the `Provider` was there or not...

**Comment by dai-shi** [comment]
Hm, again, I hadn't thought about such use cases without Provider.
But, I understand how that commit broke your logic.
Let me see if I can change the library without introducing new use cases, but at least somewhat configurable.

**Comment by dai-shi** [comment]
Please try #143.
https://ci.codesandbox.io/status/dai-shi/react-tracked/pr/143
Find "Local Install Instructions" ☝️

**Comment by totszwai** [comment]
@dai-shi that seems to do the trick! Now whether or not that is actually a good idea in the long run, but this fix seems to add much more flexibility.

```
const optionalUpdateWhenNoProvider = function (args: any) {
  console.log('No provider bro', args);
};

export const {
  Provider,
  useTrackedState,
  useUpdate
} = createContainer(useValue, { 
  defaultUpdate: optionalUpdateWhenNoProvider
});

```

<img width="473" alt="image" src="https://user-images.githubusercontent.com/4440365/158928102-b156657e-47e1-470e-a129-cc406ce95c6c.png">
