### ISSUE TITLE
Q: Syncing states between tabs

### ISSUE THREAD

**Issue by TomFreudenberg** [dai-shi/react-tracked#144]
Dear @dai-shi 

I have tried to figure out what to use best for syncing states between different tabs.

No way really was getting me fine.

I use react-tracked to work with a structured object like this:

```js
const GlobalAppStates = () =>
  useState({
    app: {
      env: VERSION.ENV,
      name: VERSION.NAME,
      version: VERSION.VERSION,
    },
    theme: {
      active: undefined,
      isLightMode: false,
      isDarkMode: false,
      prefersDarkMode: false,
    },
    i18n: {
      language: undefined
    }
  });

// we use const decompilation and renaming to export useTracked as useGlobalAppStates
const { Provider: GlobalAppContextProvider, useTracked: useGlobalAppContext } = createContainer(GlobalAppStates);

// export access to provider and states context
export { GlobalAppContextProvider, useGlobalAppContext };
```

With this it is easy for us to handle all necessary states in our app with just one provider - That is great :-)

To sync states I guess the most compatible for desktop and mobile browsers currently is using `localStore` and listening to it's `onChange` event.

Should I save the whole `struct` into `localStore` and when getting the event on a other tab - re-read and set (apply) the read values to the struct again on the other tab to signal changes to all components using `useTracked`?

Is this the best (compatible) and suggest solution?

Would be nice if you would take the time to give some more feedback in detail how you would manage that. I know - time is money - so I am willing to put some bucks on this if helpful, too.

Thanks in any way for your components and your attention
Tom

**Comment by dai-shi** [comment]
Hi, do you mean `localStorage`'s `storage` event? That should work if the state is serializable.

I would suggest to do it in `createContainer`.

Something like this?
```js
const GlobalAppStates = () => {
  const [state, setState] = useState(() => {
    const storageData = localStorage.getItem('SOME_KEY');
    return storageData ? JSON.parse(storageData) : SOME_INITIAL_DATA;
  });
  useEffect(() => {
    const callback = (e) => {
      if (e.key === 'SOME_KEY' && e.newValue) {
        setState(JSON.parse(e.newValue));
      }
    };
    window.addEventListener('storage', callback);
    return () => window.removeEventListener('storage', callback);
  }, []);
  useEffect(() => {
    localStorage.setItem('SOME_KEY', JSON.stringify(state));
  }, [state]);
  return [state, setState];
};
```

Notice, this doesn't depend on react-tracked and the same technique can be applied to the bare context use case.

**Comment by TomFreudenberg** [comment]
> Notice, this doesn't depend on react-tracked and the same technique can be applied to the bare context use case.

Sure I know 

> That should work if the state is serializable.

I already had implemented something similar like you put in code example.

I was wondering if there is any better/niftier decision to do this - but ok - as long as the "father of react states handling" (you) :-) suggest that - I will keep my implementation.

Thanks for your feedback!
Tom
