### ISSUE TITLE
[TypeScript] Unable to set propState when used with TypeScript

### ISSUE THREAD

**Issue by totszwai** [dai-shi/react-tracked#152]
TypeScript is not letting me pass the props over to the `useState` like in your example. It doesn't like `propState` as well as `useState` when passing them over to the `createContainer`
https://github.com/dai-shi/react-tracked/blob/main/website/docs/recipes.md#usestate-with-propstate

![image](https://user-images.githubusercontent.com/4440365/164535679-1cad13bf-e311-4fbb-aff6-33880e5e50f3.png)

**Comment by dai-shi** [comment]
You need to type `useValue`.
https://codesandbox.io/s/condescending-leftpad-hlokvl?file=/src/App.tsx

**Comment by dai-shi** [comment]
Closing as stale.
