### ISSUE TITLE
[Question]useImmerReducer can not be used in createContainer?

### ISSUE THREAD

**Issue by TrendAlan** [dai-shi/react-tracked#154]
Hi I got another problem when I try to use Immer, you can check the example [here](https://codesandbox.io/s/react-tracked-example-32cd6h?file=/src/context.js:564-579)
why `createContainer(useCommonReducer);` works but `createContainer(useImmerAsReducer);` can not work?

Any idea?

**Comment by dai-shi** [comment]
Seems like you failed to import it correctly?
```js
import { useImmerReducer } from "use-immer";
```

**Comment by TrendAlan** [comment]
My bad ~_~!!
