### ISSUE TITLE
Unexpected renders 

### ISSUE THREAD

**Issue by BenDmg** [dai-shi/react-tracked#155]
useReducer initialState is updating when something else in the object as changed 
`
 { value1: 'something')
 { value2: 'somethingElse')

 dispatch(forValue1) 
`
other component using Value2 ( not value1 & not a  children ) is re-rendering also and should not. 
We are using a large object for initial state ( 30 key -> value ), was this not design to handle that ?

**Comment by dai-shi** [comment]
Hi, thanks for reporting. It should work fine for such a large object.
Would you create a minimal reproduction? I think there are some misusages, or some bugs.
