### ISSUE TITLE
[Question] about peer deps

### ISSUE THREAD

**Issue by nosferatu500** [dai-shi/react-tracked#161]
Hi! Sorry for creating this issue. I don't see Discussions panel on this repo.

I have a few questions about react-tracked:

 - Why would I need to install the `scheduler` dependency if it is already listed in `yarn.lock` as a dependency for react-dom?
 - Should I install the `scheduler` dependency in my main project if I am using a library that uses `React-tracked`?

**Comment by dai-shi** [comment]
In short, it's how peer deps work. If it works for you without explicitly installing it, it's just fine for you. Some users are required to install peer deps of deps explicitly, so the note is for them.

**Comment by nosferatu500** [comment]
Thanks!
