### ISSUE TITLE
Redux DevTools Support

### ISSUE THREAD

**Issue by theskinnycoder** [dai-shi/react-tracked#163]
Would it be possible to integrate Redux DevTools when state is managed by React Tracked? Like maybe a middleware for all our stores like in Zustand, but here instead of subscribing to an external store, the devtools subscribe to the underlying React Context created by React Tracked.

**Comment by dai-shi** [comment]
It would be tricky to support redux devtools. Do you know any practice with useState and redux devtools? It can be applicable to react-tracked. 

Otherwise, react dev tools would better fit.

**Comment by theskinnycoder** [comment]
Found [this](https://youtu.be/nImE4P8Wc_M) I think maybe this is an implementation of using useState with Redux DevTools.

Code : https://github.com/jherr/redux-devtools/blob/main/hooks-test/src/App.js

**Comment by dai-shi** [comment]
Cool. If that works, you can do the same thing in your `useValue` you pass to `createContainer`. Please give it a try.

**Comment by dai-shi** [comment]
Closing as stale.
