### ISSUE TITLE
Not Working With Map Objects

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [dai-shi/react-tracked#164]
This package is fantastic! Works really well when using regular objects but not when using Map objects. Map objects seem to always trigger re-renders.

**Comment by dai-shi** [comment]
Right, it's not supported. (Too complex and technically impossible for "full" support)
Only plain objects are supported.

**Comment by Jordan-Eckowitz** [comment]
Okay, fair enough, thanks for the great work!
