### ISSUE TITLE
[v0.8] Typescript error in Provider when passing props to createContainer

### ISSUE THREAD

**Issue by chrisrzhou** [dai-shi/react-tracked#17]
I want to say I really really **LOVE** the changes in `v0.8`!

I'm running into a Typescript error when trying to use `Provider` with props that are passed into `createContainer`.

Here is a snippet of my code:

```js
// state.tsx (no typescript errors)
import * as types from 'types';

export const {
  Provider,
  useSelector,
  useUpdate: useDispatch,
} = createContainer(({ initialState, onChange }) => {
  const [state, dispatch] = useReducer(reducer, initialState);

  // this was really cool that I can wrap useReducer dispatch with whatever custom logic I 
  // want here and return a wrappedDispatch.  I see that you have a PR about ideas on 
  // implementing middlewares in react-racked, not sure if this pattern will give some ideas.
  function update(action: types.Action): void {
    dispatch(action);
    if (onChange && !blackListedActions.includes(action.type)) {
      onChange(state.filters, action);
    }
  }
  return [state, update];
});


// component.tsx (typescript error on Provider)
import { Provider} from 'state';

<Provider
  initialState={getInitialState(filters)}
  onChange={onChange}>
  <Search isDisabled={isDisabled} isLoading={isLoading} />
</Provider>
```

Over here, I see a Typescript error on `Provider` that reads:

```
src/index.tsx:45:14 - error TS2322: Type '{ children: Element; initialState: State; onChange: ChangeHandler; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode; }'.
Property 'initialState' does not exist on type 'IntrinsicAttributes & { children?: ReactNode; }'.
45             <Provider
```

It doesn't know anything about the props (`initialState`, `onChange`) that are requested when creating `createContainer`.  Is there something I have to do explicitly when creating the container to have this not complain?

## How I'm organizing my state code with `react-tracked`.
I'm a huge fan of this library, and really like the simplified approach and API.  Wanted to give some ideas how I'm using this to organize my project so far!

I like how I end my state files with exporting `react-tracked` methods, so anything state-related (actions, reducers, tracked-state, selectors) can all be consumed/imported from one file.  I can see this scale really nicely with more folders/files e.g.

```bash
/state
  /user
    index.ts  # exports reducer, actions, selectors and react-tracked APIs
    reducer.ts  # can be a single DUCKs-like file, but I re-export them to index.ts anyway.
    actions.ts
    selectors.ts
  /cart
    index.ts
    reducer.ts
    actions.ts
    selectors.ts
  /etc
    index.ts
    reducer.ts
    actions.ts
    selectors.ts
```

Excited to see where this goes, and I believe if there is integrations with middleware and dev-tooling, it will pick up rapidly.  I had some code with wrapping dispatches, but I don't know enough to see how to organize it as middlewares for `react-tracked`.  Happy to brainstorm together!  I think there **MIGHT** be ways to hack and merge the APIs into `redux-dev-tools` and piggy back on the existing `redux-dev-tools` to render state changes.

**Comment by dai-shi** [comment]
I'm so glad to hear strong positive feedback from you. You are very encouraging.

## Provider typing

I haven't tried your specific example, but you should be able to type the container.
https://github.com/dai-shi/react-tracked/blob/92c6342d69f877c9b2ced9f2fb3465a8ebac3c42/src/index.d.ts#L7-L11

Maybe something like this for typical reducer:
```ts
createContainer<State, (action: Action) => void, { initialState: State; reducer: (state: State, action: Action) => State }>(...)
```
Oh boy, this is a bit ugly. I wish it would be better. I might need a help from typescript experts...

In your use case, something like this may work:
```ts
} = createContainer(({ initialState, onChange }: { initialState: types.State; onChange?: (filters: types.Filters, action: types.Action) => void }) => {
```

## Folder structure

Very nice to see you organize files to scale.
I'd admit I'm not super good at this stuff, so your experiments/trials/suggestions are so valuable.

## Middleware

I agree it's important. Let's discuss in #8.

## DevTools

I've once tried integrating Redux DevTools Ext in [my other library](https://github.com/dai-shi/react-hooks-global-state), which was a disaster. I think hacking Redux DevTools for non-Redux lib correctly requires too much effort.

The good news is that React now has a new [DevTools](https://ja.reactjs.org/blog/2019/08/15/new-react-devtools.html).
My hope is that we can simply inspect the state in the provider that is created by `createContainer`. Haven't tried it, but that's my plan. I am interested, and would definitely try it some time later.

**Comment by chrisrzhou** [comment]
issue resolved, your suggestion works when explicitly typed!
