### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by daliborkoenig** [dai-shi/react-tracked#176]
Managed to get it to work, it was my wrong setup of the system.

Looking forward to using it in the project.

Thank you for your time.

**Comment by dai-shi** [comment]
Hi, can you try creating a small reproduction with https://codesandbox.io/s/react-new ?

**Comment by daliborkoenig** [comment]
Unfortunatelly I can't now as i moved to try out zustand. Would really like to move back to this one as it seems it is exactly what i need. It is awesome, from what I can tell.

I am making a weird mini tables library for our project where I need 1-5 tables with 1-5 rows with 13-14 cells each. Data is coming from 4 different sources. Only some rows need to be editable and in those only some cells are editable. And from there I need to track the data changes per cell to create sum rows and sum columns. And ofc, it doesn't help that the last table is a sum of sum rows and sum of sum columns. Biggest hurdle was re-rendering on cell change. I think this awesome package could help a lot with that.

I can tell you i copied the code exactly as it is in many of your examples and every time i tried to update the store i would get this error. I have Typescript 4.4.3 installed in the project if that helps. and this is my tscofing:

{
  "compilerOptions": {
    "target": "ES6",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src/**/*", ".storybook/**/*", "src/views/Private/Account/AccountAboPage/.tsx"],
  "typedocOptions": {
    "name": "Haufe Better Business - UI Documentation",
    "excludeExternals": true,
    "entryPoints": ["./src"],
    "out": "docs/library",
    "theme": "default"
  }
}

Hope it helps.

**Comment by dai-shi** [comment]
What I can tell from the error message is that your usage is invalid somewhere. Can't tell. Hope you can try something. Anyways, zustand is also a nice library, and recommended if what you need is a module (global) state.

**Comment by daliborkoenig** [comment]
used this one 
https://codesandbox.io/s/react-tracked-example-mkl5f?file=/src/ReactTracked.tsx

just copied it to try to get it working. And i got the error on trying to update the name.

zustand is nice, but I don't need a global state, jsut a state tracking this one set of components.

**Comment by daliborkoenig** [comment]
![image](https://user-images.githubusercontent.com/29024886/216842040-48d9ea74-fd33-4813-accc-069849aba5e5.png)


here is an image of what i get in inspect.

**Comment by daliborkoenig** [comment]
This code is where i initiate it.

import { createContainer } from "react-tracked";

const initialState = {
  firstName: "Harry",
  familyName: "Potter",
};

type State = typeof initialState;
type Action =
  | { type: "setFirstName"; firstName: string }
  | { type: "setFamilyName"; familyName: string };

const reducer: Reducer<State, Action> = (state, action) => {
  switch (action.type) {
    case "setFirstName":
      return { ...state, firstName: action.firstName };
    case "setFamilyName":
      return { ...state, familyName: action.familyName };
    default:
      throw new Error("unexpected action type");
  }
};

export const { Provider, useTracked } = createContainer(
  () => useReducer(reducer, initialState),
  true
);

const DTables: FC<TableContainerProps> & {
  Table: FC<TableProps>;
  Head: FC;
  TBody: FC;
  Foot: FC;
  HCell: FC<CellProps>;
  Row: FC;
  Cell: FC<CellProps>;
} = ({ children, ...rest }) => {
  return (
    <Provider>
      <StyledTablesContainer {...rest}>{children}</StyledTablesContainer>
    </Provider>
  );
};

**Comment by daliborkoenig** [comment]
and this is where i try dispatch

const TablesTest: FC = () => {
  const PDTablesArray = useSelector(
    ({ planning: { PDTablesArray } }: ILocalState) => PDTablesArray,
    isEqual
  );
  console.log(PDTablesArray);
  const [state, dispatch] = useTracked();
  dispatch({ type: "setFirstName", firstName: "whatever" });
  const addTablesItem = useTablesStore((state) => state.addTable);

  if (!PDTablesArray) return null;
  return (
    <DTables grid={PDTablesArray.length}>
      {PDTablesArray &&
        PDTablesArray.map((table, i) => {
          addTablesItem(table.code);
          return (
            <TemplateTableWrapper key={`table-${table.code}`}>
              <DetailsHeadline>{table.title}</DetailsHeadline>
              <TableTest tableIndex={i} tableData={table} />
            </TemplateTableWrapper>
          );
        })}
    </DTables>
  );
};

**Comment by dai-shi** [comment]
Can you put those code snippet in https://codesandbox.io/s/react-tracked-example-mkl5f?file=/src/ReactTracked.tsx and remove unused code and files to simplify it?

**Comment by daliborkoenig** [comment]
It works on codesandbox when i put the code. As it is the same code.

It also works when I port it in to a clean TS project.

But when I try to run it in my project i get that error. 

I am thinking it might be something with tsconfig, but i can't find figure out what.

Anyhow, definatelly thank you for your time. If you think of something, please let me know.
