### ISSUE TITLE
Can you use zustand's getState() with react-tracked?

### ISSUE THREAD

**Issue by mglavall** [dai-shi/react-tracked#181]
I'm currently trying to integrate react-tracked with my zustand project to make selectors easier to read. But is complaining when I use `getState()`. Is there any limitation around this? 

Codesandbox: https://codesandbox.io/s/zen-liskov-c702ih?file=/src/App.js:439-454

Thank you so much in advance.

**Comment by dai-shi** [comment]
You probably need to copy it.
```js
const useTrackedStore = createTrackedSelector(useStore);
useTrackedStore.getState = useStore.getState;
// or Object.assign(useTrackedStore, useStore)
```
Hope it works.

**Comment by dai-shi** [comment]
Closing as stale.
