### ISSUE TITLE
Unused stores lead to renders

### ISSUE THREAD

**Issue by andyyxw** [dai-shi/react-tracked#183]
I use `useTrackedStore` returned by `createTrackedSelector(useStore)` with `zustand`, there are no properties of store used in the current component, but any changes in the store will result in a render of the component.
Please help me understand this behaviour, thanks!

![image](https://user-images.githubusercontent.com/41931722/230920815-f610ee43-cac1-4eaf-b817-d1ccefb4ede9.png)
https://codesandbox.io/s/react-typescript-forked-l6k6lv?file=/src/App.tsx:1049-1064

**Comment by dai-shi** [comment]
This is an intended behavior by design.
If you don't touch a property of an object, the library assumes that the whole object is "used".

```js
const state = useTrackedStore();
// The whole `state` is marked as used, if you don't use `state` properties.

const { obj } = useTrackedStore();
// In this case, `obj` is marked as used, if you don't use `obj` properties.
```

**Comment by andyyxw** [comment]
> This is an intended behavior by design. If you don't touch a property of an object, the library assumes that the whole object is "used".
> 
> ```js
> const state = useTrackedStore();
> // The whole `state` is marked as used, if you don't use `state` properties.
> 
> const { obj } = useTrackedStore();
> // In this case, `obj` is marked as used, if you don't use `obj` properties.
> ```

@dai-shi Thanks, I've understood it. Can you tell me the code related to this behaviour, is it in `proxy-compare`?

**Comment by dai-shi** [comment]
Yeah, it's proxy-compare.
