### ISSUE TITLE
useMemo skipped re-render 

### ISSUE THREAD

**Issue by BruceSuperProgramer** [dai-shi/react-tracked#189]
In the useMemo(, [dependencies]), dependencies included one or more properties come from useTrackedState. I found even property changed however useMemo won't really re-render. I have to get ride of useMemo and using component instead and wrapped component with memo that coming from react-tracked.

Could we have an useMemo function come from react-tracked same as memo function. React.memo and useMemo just not working well with react-tracked objects.

**Comment by dai-shi** [comment]
AFAIR, the reason we don't export custom useMemo is it's likely that there's a workaround. And, `useMemo` usually doesn't work for better performance.
The suggested workaround is:
```js
const somePrimitiveValue = trackedObj.prop;
useMemo(..., [somePrimitiveValue]);
```
If you still want `useMemo(..., [trackedObj])`, you could directly import `trackMemo` from `proxy-compare`:
```js
trackMemo(trackedObj);
useMemo(..., [trackedObj]);
```

**Comment by BruceSuperProgramer** [comment]
Hi @dai-shi  Thanks for the quick reply. I tried both approaches and found selectedSubcontractors still unable to re-render even responsibleParties changed.
<img width="750" alt="Screenshot 2023-08-01 at 10 32 23 am" src="https://github.com/dai-shi/react-tracked/assets/46988290/e26a352d-2414-45e5-b033-bc8236a1f310">

**Comment by dai-shi** [comment]
Not 100% sure, but from your code, it doesn't seem useMemo is necessary. Can you try removing it?

**Comment by BruceSuperProgramer** [comment]
@dai-shi It is necessary I don't want to selectedSubcontractors re-run when only inspection is being changed and responsible parties remain unchanged. Removing useMemo it will work but I do need to memorize this value.

**Comment by dai-shi** [comment]
Okay, if useMemo is necessary, my next question is why `trackMemo(...)` doesn't work. What would happen if you `trackMemo(responsibleParties)`? Note that it doesn't return anything.

**Comment by BruceSuperProgramer** [comment]
Oh yes, I tried again. It works, previously I don't know why it doesn't work but now it works.
<img width="793" alt="Screenshot 2023-08-01 at 1 08 08 pm" src="https://github.com/dai-shi/react-tracked/assets/46988290/1ae27814-8eae-42f1-b52f-a21bdf8cb512">

**Comment by dai-shi** [comment]
Yeah, that looks good.

**Comment by BruceSuperProgramer** [comment]
Cool thanks for your help @dai-shi
