### ISSUE TITLE
React-tracked crashes with in react-native expo sdk-49

### ISSUE THREAD

**Issue by sfl-moneytree** [dai-shi/react-tracked#193]
Hello,

I've been using React-tracked with no issue for a while.
When upgrading to expo sdk49 which means using react 18.2.0, react-native 0.72.4 and running a basic example, React tracked 1.7.11 crashed on Provider creation (was working smoothly on sdk48).
Error: Not implemented. index.native.modern.js 1:444

Any help is welcome

**Comment by dai-shi** [comment]
Thanks for reporting.

Does metro bundler change something? I'm not sure why they look for `index.native.modern.js`...
I need someone to help on this.

**Comment by sfl-moneytree** [comment]
ok seems to have found the reason.
use-context-selector package has a file called batchedUpdates.ts
with export { unstable_batchedUpdates as batchedUpdates } from "react-dom";

and installing react-dom fix the issue, depencies was somehow missing, and you need to explcitely install it in expo sdk49. (not required in sdk48...not sure why)

Anyway thanks a lot

**Comment by dai-shi** [comment]
We have that for react-native too.
https://github.com/dai-shi/use-context-selector/blob/bd4eb7492f0c2cfe9a1050ce924cf46c2f1b1150/src/batchedUpdates.native.ts#L3

> I'm not sure why they look for `index.native.modern.js`...

That was my overlook. We have that defined in package.json
https://github.com/dai-shi/use-context-selector/blob/bd4eb7492f0c2cfe9a1050ce924cf46c2f1b1150/package.json#L13

So, I guess new react-native has changed something. There should a way to fix it.

**Comment by orkanylmz** [comment]
any news about this?

**Comment by dai-shi** [comment]
I think I need someone's help.

> Error: Not implemented. index.native.modern.js 1:444

This is the only information provided.

Wait, where it it exactly?
https://unpkg.com/use-context-selector@1.4.1/dist/index.native.modern.js
<img width="995" alt="image" src="https://github.com/dai-shi/react-tracked/assets/490574/1e0b08be-6dad-4d73-9142-5768e9a8fc0a">
That's `1:444`. I wonder what is "Not implemented".

**Comment by dai-shi** [comment]
Somewhere like this: https://github.com/dai-shi/use-context-selector/blob/bd4eb7492f0c2cfe9a1050ce924cf46c2f1b1150/src/index.ts#L32-L34

I'm not sure.

> and installing react-dom fix the issue

and, that's also interesting. Why installing `react-dom` fixes `index.native.modern.js`...

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-tracked/v/1.7.12
