### ISSUE TITLE
nested object in useTracked is treated as unchanged in some component, meanwhile it is treated as changed in some other component 

### ISSUE THREAD

**Issue by peter1997546** [dai-shi/react-tracked#194]
Here's some of the code snippet...

![image](https://github.com/dai-shi/react-tracked/assets/23149848/47a51c16-9eee-4926-92db-36dfed23ef2c)

We pass the setState returned in useTracked
And you can see there's spread operator to create a new object assigned in initialForms property
![image](https://github.com/dai-shi/react-tracked/assets/23149848/cc76cbd0-e289-474f-90b9-07d80591cfcb)

There're two places that passed initialForms as a dependency in useEffect

![image](https://github.com/dai-shi/react-tracked/assets/23149848/f3746a52-312c-4522-a3c2-43e3a20cd543)
![image](https://github.com/dai-shi/react-tracked/assets/23149848/8e4b32fe-08af-4db2-826d-5e83b88b7d76)

However only one callback in useEffect in Form Detail is called...
![image](https://github.com/dai-shi/react-tracked/assets/23149848/5628fc7e-c41c-43c3-a132-f60c7a0041f2)

And it's a little weird that if we removed this part of code.
Then everything works fine...
![image](https://github.com/dai-shi/react-tracked/assets/23149848/d83b8135-551a-48a6-a627-211ddc71db0e)
![Uploading image.png…]()

**Comment by dai-shi** [comment]
Is it correct that you don't have any issues if you don't have `useEffect`?

**Comment by peter1997546** [comment]
> Is it correct that you don't have any issues if you don't have `useEffect`?

No it's not. I've some other function taking the ”initialForms” as a parameter.
However it's not able to retrieve the latest updated object.

**Comment by peter1997546** [comment]
> Hmm, can you create a minimal reproduction? Just one file with a few lines as possible. CodeSandbox is preferred.

Here's the CodeSandBox to reproduce the problem

https://codesandbox.io/s/react-18-typescript-forked-wjhf84

In ProblematicComponent, it's referring to a unchanged field
It also has a button that print a debug log to simulate save function.

Inside ProblematicComponent, there're two buttons that is updating field1/field2 in the nested object.
You can see that their value is actually getting updated.
But once you click the save button, you will see the debug log is still printing the original object.

Weird thing is that if you delete line 53 in App.tsx, you would see the save button is now able to get the updated object again...

**Comment by dai-shi** [comment]
This is working as expected from the library perspective.
With L53, it tracks only `unchangedField` and changing other fields doesn't trigger rerenders.

Basically, as you want to use the entire object, one valid workaround is to copy the object in render, which will be used in callbacks: https://codesandbox.io/s/react-18-typescript-forked-34gln2

**Comment by peter1997546** [comment]
> This is working as expected from the library perspective. With L53, it tracks only `unchangedField` and changing other fields doesn't trigger rerenders.
> 
> Basically, as you want to use the entire object, one valid workaround is to copy the object in render, which will be used in callbacks: https://codesandbox.io/s/react-18-typescript-forked-34gln2

Got it. Might I say that once we track any property inside a object
It's no longer able to track changes of the whole object? (Without those workarounds)

**Comment by dai-shi** [comment]
Yes, that behavior is _the goal_ of this library.

**Comment by peter1997546** [comment]
> Yes, that behavior is _the goal_ of this library.

I thought it tracks both nestedObject itself and nestedObject.unchangedField in this case since we are using both of them🤔

**Comment by dai-shi** [comment]
that's theoretically impossible because
```js
// use both
const nestedObject = state.nestedObject;
const someValue = nestedObject.someValue;

// just use the value
const someValue = state.nestedObject.someValue;
```
We can't distinguish those two ways with proxies. (it will require static analysis)
