### ISSUE TITLE
useTrackedState causing re-render?

### ISSUE THREAD

**Issue by mewtwoo** [dai-shi/react-tracked#195]
https://codesandbox.io/s/clever-cerf-588tt9

Every time I click the button to update state in Age component, the Name component `console.count` to Console.

**Comment by dai-shi** [comment]
That's how it works.
It renders then bails out, and there's no commit (which is a costly task.)

Wrapping with `useEffect` leads to intuitive result.
https://codesandbox.io/s/optimistic-field-qspqd9


See also #177

**Comment by dai-shi** [comment]
Closing as stale.
