### ISSUE TITLE
React Compiler and tracking

### ISSUE THREAD

**Issue by avedetvedea** [dai-shi/react-tracked#197]
When React Forget lands, will react-tracked continue to be useful?

**Comment by dai-shi** [comment]
Conceptually, it will still be useful as Forget doesn't optimize for Context.
However, Forget will probably break React-Tracked depending on the usage (which is true for `useMemo` as of now.)

**Comment by dai-shi** [comment]
https://twitter.com/dai_shi/status/1763701256105922719

**Comment by dai-shi** [comment]
#202 will make this library survive with React Forget.
