### ISSUE TITLE
Immer

### ISSUE THREAD

**Issue by j2is** [dai-shi/react-tracked#2]
https://github.com/immerjs/immer

**Comment by dai-shi** [comment]
Do you want to use react-tracked with immer?
I haven't tried it here, but I've done it with reactive-react-redux.
https://github.com/dai-shi/reactive-react-redux/tree/master/examples/04_immer
As long as immer works with `useReducer`, it probably works.

**Comment by dai-shi** [comment]
https://github.com/dai-shi/react-tracked/tree/master/examples/07_todolist
This example uses immer. Please check that out.

Closing this for now unless there's further discussion.
