### ISSUE TITLE
Crash at dev mode

### ISSUE THREAD

**Issue by C-zhui** [dai-shi/react-tracked#214]
in this file:  https://github.com/dai-shi/react-tracked/blob/main/src/createTrackedSelector.ts
this line: `    if (typeof process === 'object' && process.env.NODE_ENV !== 'production') {  `
my bundler will replace `process.env.NODE_ENV` with `development`, but  `process` is `undefined`.

then, some lazy module federation will add add `process` to `window` for some reason... 
be like `globalThis.process = { env: { NODE_ENV: '' } }`

when run into the code above, it will run 
`      useAffectedDebugValue(state, affected);`

break the react hook's rule, then crash.

**Comment by dai-shi** [comment]
Can't you configure your bundler so that it replaces `process` with `{}`?

**Comment by C-zhui** [comment]
😂 so I add `window.process = {}` to `index.tsx` to fix that now.

**Comment by C-zhui** [comment]
> Can't you configure your bundler so that it replaces `process` with `{ env: { NODE_ENV: 'development' } }`?

No, when  I replace `process` with `{...}`, it will affect the code like `process.nextTick(()=>{})`. 
Bundler need to transform `process.nextTick(()=>{})` to something like `promise.resolve().then(()=>{})`.
But it becomes `{}.nextTick`.
I haven't found a good way yet.

**Comment by dai-shi** [comment]
Does it help to have a module-level const variable?

```js
const hasGlobalProcess = typeof process === 'object';
```

<img width="1363" alt="image" src="https://github.com/user-attachments/assets/1d227553-4848-4acd-8ff4-b2573a2bfe80">

**Comment by C-zhui** [comment]
> Does it help to have a module-level const variable?
Great! I think it works!

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/react-tracked/v/2.0.1
