### ISSUE TITLE
[Question] Why does re-rendering occur even when using React.memo?

### ISSUE THREAD

**Issue by sangsang-6914** [dai-shi/react-tracked#226]
hello, dai-shi!
While studying your book, “Micro State Management with React Hooks,” I encountered an issue. In the example below, when count changes, only the Counter component should re-render. However, it seems that the re-render optimization is not working as expected.

**Issue Code**
```
import { memo, useState } from "react";
import { createContainer } from "react-tracked";

const useValue = () => useState({ count: 0, text: "hello" });

const { Provider, useTracked } = createContainer(useValue);

const Counter = memo(() => {
    const [state, setState] = useTracked();
    const inc = () => {
        setState((prev) => ({ ...prev, count: prev.count + 1 }));
    };
    return (
        <div>
            count: {state.count} <button onClick={inc}>+1</button>
        </div>
    );
});

const TextBox = memo(() => {
    const [state, setState] = useTracked();
    const setText = (text: string) => {
        setState((prev) => ({ ...prev, text }));
    };
    return (
        <div>
            <input value={state.text} onChange={(e) => setText(e.target.value)} />
        </div>
    );
});

const App = () => (
    <Provider>
        <div>
            <Counter />
            <Counter />
            <TextBox />
            <TextBox />
        </div>
    </Provider>
);

export default App;
```

Even when the count changes, the TextBox component is re-rendering, and I can’t figure out why.
I confirmed that re-rendering is occurring by using the “Highlight updates when components render.” feature in Chrome React DevTools.

**Comment by simjieun** [comment]
I am experiencing the same issue as well.

**Comment by dai-shi** [comment]
Thanks for reading the book!


> I confirmed that re-rendering is occurring by using the “Highlight updates when components render.” feature in Chrome React DevTools.

If you try console.log in useEffect and it behaves as expected, then it's a designed behavior from `use-context-selector`.

> even when using React.memo?

BTW, in this use case, `memo` doesn't help anyway.

**Comment by dai-shi** [comment]
Yeah, confirmed that: https://stackblitz.com/edit/vitejs-vite-sm1mvc?file=src%2FApp.tsx&terminal=dev

This is related issue: https://github.com/dai-shi/use-context-selector/issues/142

We could use a different implementation of use-context-selector, but that will lose some capabilities.
Instead, the recommendation in practice is to use zustand+react-tracked or valtio.

**Comment by simjieun** [comment]
Thank you for the quick response.
Should I consider the re-rendering to be intentional?

**Comment by dai-shi** [comment]
Yes, it's necessary to be concurrent rendering friendly.
FYI: https://github.com/dai-shi/will-this-react-global-state-work-in-concurrent-rendering

If this behavior causes real performance issue, our solution is to memoize heavy computation with something like useMemo.

Having that said,

> using the “Highlight updates when components render.”

it's really bad that it doesn't work with React DevTools.

Have you considered React-Tracked with Zustand?

**Comment by sangsang-6914** [comment]
Thank you, Daishi Kato. I understand it clearly now!

**Comment by dai-shi** [comment]
> We are currently conducting a study using Daishi Kato's book, which is why we reached out with this question.

Cool.

Thanks, both of you!
