### ISSUE TITLE
Get current state of useTrackedState() 

### ISSUE THREAD

**Issue by fortezhuo** [dai-shi/react-tracked#28]
Hi. 
Thanks for the nice library, but I found an issue that I want to access current state of the tracked state ?
So how to implement useRef on tracked state so I can get latest / current state ..

Source of inspiration : https://blog.castiel.me/posts/2019-02-19-react-hooks-get-current-state-back-to-the-future/

**Comment by dai-shi** [comment]
Hi, could you elaborate what you would like to do?

You could basically use a tracked state as a normal state, with some caveats.
If you want a previous state, you should be able to do like this:
```js
  const state = useTrackedState()
  const stateRef = useRef(state)
  useEffect(
    () => { stateRef.current = state },
    [state]
  )
```
Hm, I actually never tried this. If there's an issue, I will investigate it.

This is not a good usage, because we now use `state` which always changes even if a small part of the state is changed. So, I would really want to understand the real use case.

**Comment by fortezhuo** [comment]
I have created function for "base" like this

```
const defaultState: State = {
  data: {},
  temp: { isProcessing: false, isReload: false },
  error: null
}
export const useGlobal = (initState = defaultState) => {
  const {
    Provider,
    useTracked,
    useTrackedState,
    useUpdate
  } = createContainer(() => useState(initState))
  const useMethod = () => {
    const update = useUpdate()
    const setState = useCallback(
      (type: string, value: any) => {
        update(prev => {
          const data =
            type === "data" ? { ...prev.data, ...value } : { ...prev.data }
          const temp =
            type === "temp" ? { ...prev.temp, ...value } : { ...prev.temp }
          const error = type === "error" ? value : prev.error
          return { data, temp, error }
        })
      },
      [update]
    )
    const setData = (value: any) => setState("data", value)
    const setTemp = (value: any) => setState("temp", value)
    const setError = (err: any) => {
      if (err == undefined) {
        setState("error", null)
      } else {
        const { response, config } = err
        const responseType = config ? config.responseType : ""
        setState(
          "error",
          responseType == "blob"
            ? {
                status: response.status,
                statusText: response.statusText,
                stackTrace:
                  "Stack Trace is not provided, please check Domino Log",
                request: config
              }
            : response
            ? {
                status: response.status,
                statusText: response.statusText,
                stackTrace: response.data.error,
                request: config
              }
            : err.message === "Session Expired / Authentication Error" ||
              err.message === "Network Error"
            ? { status: 401, statusText: err.message }
            : { status: 0, statusText: err.message }
        )
      }
    }

    return {
      setState,
      setData,
      setTemp,
      setError
    }
  }

  return {
    Provider,
    useTracked,
    useTrackedState,
    useUpdate,
    useMethod,
    getUntrackedObject
  }
}
```
And I use the above function like this

```
import { useGlobal, State } from "./useBase"
import { api } from "../api"

const initState: State = {
  data: {},
  fatalError: null,
  temp: {},
  error: null
}

export const {
  Provider,
  useTracked,
  useTrackedState,
  useUpdate,
  useMethod
} = useGlobal(initState)

export const useAction = () => {
  const state = useTrackedState()
  const { setState, setData, setError } = useMethod()
  const setFatalError = (err: any) => {
    setState("fatalError", err)
  }
  const login = async () => {
    const { username = "", password = "", domain = "" } = state.data //<== the state is not current / latest (I can't get username / password that I typed on Form)
    try {
      setState("temp", { isProcessing: true })
      if (username == "" || password == "" || domain == "") {
        throw new Error("Please fill User Name, Password, & Domain")
      }
      const res = await api.login(username, password, domain)
      if (res.data.success) {
        // Login
      } else {
        throw new Error(res.data.message)
      }
    } catch (err) {
      setError(err)
    } finally {
      setState("temp", { isProcessing: false })
    }
  }
  return { setFatalError,  login }
}
```

Form Login
```
import React, { useEffect } from "react"
import { app } from "../../hooks"
import { StyleSheet, Image } from "react-native"
import { Surface, Button } from "react-native-paper"
import { Input, Container } from "../../components"

const logo = require("../../../assets/images/logo.png")

export const Login = function Form({ navigation }: any) {
  const state = app.useTrackedState()
  const action = app.useAction()

  useEffect(() => {
    if (state.data.isLogged) {
      navigation.navigate("home")
    }
  }, [state.data.isLogged])

  return (
    <Container hook={app} toast gradient style={styles.background}>
      <Image source={logo} style={styles.logo} />
      <Surface style={styles.box}>
        <Input.Text autoFocus hook={app} name="username" label={"User Name"} />
        <Input.Password hook={app} name="password" label={"Password"} />
        <Input.Select
          hook={app}
          data={(state.temp.domain || []).map(domain => ({
            id: domain.domain,
            label: domain.domain
          }))}
          name="domain"
          search={false}
          label={"Domain"}
        />
        <Button
          loading={state.temp.isProcessing}
          disabled={state.temp.isProcessing}
          contentStyle={styles.button}
          mode="contained"
          onPress={action.login}
        >
          Login
        </Button>
      </Surface>
    </Container>
  )
}

const styles = StyleSheet.create({
  box: {
    width: 350,
    padding: 20,
    borderRadius: 10,
    top: 120,
    alignSelf: "center"
  },
  background: {
    flex: 1,
    justifyContent: "flex-start"
  },
  logo: {
    top: 80,
    width: 315,
    height: 70,
    alignSelf: "center"
  },
  button: {
    paddingVertical: 10
  }
})
```

And one of Input Component
```
import React, { FC, memo } from "react"
import { StyleSheet } from "react-native"
import { TextInput } from "react-native-paper"

type Props = React.ComponentPropsWithoutRef<typeof TextInput> & {
  label?: string
  hook: any
  type?: string
  name: string
  style?: any
}

export const InputText: FC<Props> = memo(
  ({ hook, type = "data", name, style, ...rest }) => {
    const state = hook.useTrackedState()
    const { setState } = hook.useMethod()
    return (
      <TextInput
        style={[styles.default, style]}
        value={state[type][name] || ""}
        onChangeText={text => setState(type, { [name]: text })}
        {...rest}
      />
    )
  }
)

const styles = StyleSheet.create({
  default: {
    marginBottom: 5
  }
})
```

**Comment by dai-shi** [comment]
Thanks for the use case.

> const { username = "", password = "", domain = "" } = state.data //<== the state is not current / latest (I can't get username / password that I typed on Form)

The reason this state is not updated is that this line is in callback, which means it does not **use** the state in render.
The easiest fix would be to move this line out of `login()` and put in `useAction()`.

Let me know if that works for you.

**Comment by fortezhuo** [comment]
I have moved the line like this

```
export const useAction = () => {
  const state = useTrackedState()
  const { username = "", password = "", domain = "" } = state.data // moved line
const { setState, setData, setError } = useMethod()
  const setFatalError = (err: any) => {
    setState("fatalError", err)
  }
  const login = async () => {
    try {
      setState("temp", { isProcessing: true })
      if (username == "" || password == "" || domain == "") {
        throw new Error("Please fill User Name, Password, & Domain")
      }
      const res = await api.login(username, password, domain)
      if (res.data.success) {
        // Login
      } else {
        throw new Error(res.data.message)
      }
    } catch (err) {
      setError(err)
    } finally {
      setState("temp", { isProcessing: false })
    }
  }
  return { setFatalError,  login }
}
```
And it works, but I got another lagging issue while I am typing on input text. I think the component still re-render..

**Comment by dai-shi** [comment]
Yeah, useAction triggers re-renders.
To fix the lagging, try creating a component like `<Input.Button>` and useAction only in that component. With that, only `<Input.Text>` and `<Input.Button>` would re-render.

While carefully using this library should work, in general, I'd recommend not using global state for form values. Either use any form libraries, or you can use React.useState and React.memo without any libraries.

Looking back your example, I guess if you use react-tracked, you don't need to use React.memo, so that's one plus. Note that react-tracked is not only for a single global state, but for any shared states. (Maybe, you are already using so.)

**Comment by fortezhuo** [comment]
Thanks.

After I follow your suggestion to create new Button Component and move useAction into the new one. The lagging problem disappears. And I will refactor my scripts based on your suggestion.

**Comment by dai-shi** [comment]
You are welcome.

One minor note: your `useGlobal` is not a custom hook, so I would name it like `createGlobal` to avoid possible confusion.

**Comment by peterDijk** [comment]
> Thanks for the use case.
> 
> > const { username = "", password = "", domain = "" } = state.data //<== the state is not current / latest (I can't get username / password that I typed on Form)
> 
> The reason this state is not updated is that this line is in callback, which means it does not **use** the state in render.
> The easiest fix would be to move this line out of `login()` and put in `useAction()`.
> 
> Let me know if that works for you.

Hi dai-shi,

I have a sort of similar issue: useCustomHook1 takes the state from react-tracked, and in the body of the hook a function is defined that does something based on a value in the state. 
I don't understand that you say 'this line is in callback' it's not in a callback, right? 
And even if I would wrap it in a callback, I should be able to add that state-value in de callback dependency array?

**Comment by dai-shi** [comment]
@peterDijk Hi, "this line is in callback" means "in callback." Would you have a code snippet, or codesandbox?

**Comment by peterDijk** [comment]
Hi! Thanks for quick reply!
i meant that in the example code above, I don't see the `login` function wrapped with useCallback.

Anyway, I'm trying to replicate my use case in the todo example.
Strangely, here it works. 
https://codesandbox.io/s/priceless-bash-elgkv?file=/src/hooks/useTest.ts
In my application, within the function (`setStatus` in this example) the state value is not updated..

**Comment by dai-shi** [comment]
> i meant that in the example code above, I don't see the login function wrapped with useCallback.

I see. useCallback was not important in that context.

> Strangely, here it works.

That's probably because you have console.log in render.

If you don't use `state.status` in render, it may not be tracked.
So, it's better to dispatch the action anyway and check the previous value in the reducer.
