### ISSUE TITLE
Select() function does not work with use-saga-reducer

### ISSUE THREAD

**Issue by evanrolfe** [dai-shi/react-tracked#29]
**The problem:**
Calling `yield select()` inside a saga always returns the initial state, and not the actual current state. I need to access the current state inside a saga function, is there a different way to do this or is this a bug that needs fixing?

**Steps to reproduce:**
In [examples/13_saga/src/store.ts](https://github.com/dai-shi/react-tracked/blob/master/examples/13_saga/src/store.ts), import `select` from redux-saga/effects:
```ts
import {
  call,
  put,
  delay,
  takeLatest,
  takeEvery,
  all,
  select
} from 'redux-saga/effects';
```

And change `delayedDecrementer()` to be:
```ts
function* delayedDecrementer() {
  const count = yield select(state => state.count);
  console.log(`The count is: ${count}`)
  yield delay(500);
  yield put({ type: 'DECREMENT' });
}
```
Now, open the app in the browser, click the plus button a few times so the count equals `3` (or any number > 0). Then click "-1 Delayed" button.

**What actually happens:**
The console logs display the message `The count is: 0`.

**What should happen:**
The console logs should show the actual count value before the decrement i.e. `The count is: 3`.

**Comment by dai-shi** [comment]
Hi, thanks for reporting.
It looks like a bug in use-saga-reducer.

if I add
```js
    useEffect(() => {                                                      
      stateRef.current = state;
    });
```
right after `const stateRef = useRef(state);`,
it seems to work.
(I'm not sure if useEffect runs too late and this care requires useLayoutEffect.)

@azmenak Would you take a look please?

**Comment by evanrolfe** [comment]
@dai-shi thank you for the quick response!

I can confirm that adding that `useEffect()` call does seem to fix the problem.

**Comment by dai-shi** [comment]
Closing this as I filed the issue in the upstream: https://github.com/azmenak/use-saga-reducer/issues/1

**Comment by azmenak** [comment]
Update: issue has been resolved in `use-saga-reducer`
