### ISSUE TITLE
can we use redux thunks with this?...

### ISSUE THREAD

**Issue by cocodrino** [dai-shi/react-tracked#3]
Hi, this project seems great but you didn't mention nothing about thunks and it's not clear if we can use middlewares here...would be possible use thunks for async operations with this lib?

thank you so much

**Comment by dai-shi** [comment]
No, this library is non-Redux. Please use https://github.com/dai-shi/reactive-react-redux for your purpose. reactive-react-redux v4 has the identical hooks API to react-tracked. `npm install reactive-react-redux@next`

Historically, I’ve been developing reactive-react-redux for months and react-tracked is just removing redux from reactive-react-redux for users who don’t need Redux middlewares and Redux devtools.

**Comment by cocodrino** [comment]
oh perfect, thank you
