### ISSUE TITLE
Saga example in codesandbox doesn't work

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/react-tracked#32]
The link in README.md
<https://codesandbox.io/s/github/dai-shi/react-tracked/tree/master/examples/13_saga>
doesn't work online.

It does work if you download the zip file and run locally.

Is this an issue in codesandbox?

**Comment by fuleinist** [comment]
feels like something went wrong within useSagaReducer.... both generator functions are not executed. redux-saga is working fine for sure.

**Comment by azmenak** [comment]
Spent some time to look into this today, unfortunately haven't had much luck tracking down the issue.

Can confirm it works locally, but not on codesandbox. They are a bit of a black box though, had to say what they are doing that might be causing problems.

**Comment by dai-shi** [comment]
No luck so far...

**Comment by dai-shi** [comment]
Confirmed it's fixed on my end.

@azmenak Thanks!
