### ISSUE TITLE
Several TypeScript type problems

### ISSUE THREAD

**Issue by lukejagodzinski** [dai-shi/react-tracked#36]
Hey, thanks again for the great package! I'm trying to switch my project from redux to react-tracked and overall everything works but I've encountered several typing problems that are a little bit annoying but I'm not big TS expert to find solution for them. However, I've prepared [reproduction repository](https://codesandbox.io/s/sad-meadow-tcwzt) and I'm going to describe all the cases.

**1. The `useValue` return type not compatible when using `useReducerAsync` with destructuring.**

Let's consider such code example:

```ts
const useValue = () => {
  const [state, dispatch] = useReducerAsync<
    Reducer<State, Action>,
    AsyncAction,
    AsyncAction
  >(reducer, initialState, asyncActionHandlers);
  /* some code goes here... */
  return [state, dispatch];
};
```

Now if I try to use it:

```ts
export const {
  Provider: StateProvider,
  useUpdate: useDispatch,
  useSelector
} = createContainer(useValue);
```

I will get type error for the `useValue`:

```
const useValue: () => (State | Dispatch<{
    type: "SET_VALUE";
    value: number;
} | {
    type: "SET_LOADING";
    loading: boolean;
} | AsyncActionLoadValueWait | AsyncActionLoadValue>)[]
Argument of type '() => (State | Dispatch<{ type: "SET_VALUE"; value: number; } | { type: "SET_LOADING"; loading: boolean; } | AsyncActionLoadValueWait | AsyncActionLoadValue>)[]' is not assignable to parameter of type '(props?: unknown) => [State | Dispatch<{ type: "SET_VALUE"; value: number; } | { type: "SET_LOADING"; loading: boolean; } | AsyncActionLoadValueWait | AsyncActionLoadValue>, State | Dispatch<...>]'.
  Type '(State | Dispatch<{ type: "SET_VALUE"; value: number; } | { type: "SET_LOADING"; loading: boolean; } | AsyncActionLoadValueWait | AsyncActionLoadValue>)[]' is missing the following properties from type '[State | Dispatch<{ type: "SET_VALUE"; value: number; } | { type: "SET_LOADING"; loading: boolean; } | AsyncActionLoadValueWait | AsyncActionLoadValue>, State | Dispatch<{ type: "SET_VALUE"; value: number; } | { ...; } | AsyncActionLoadValueWait | AsyncActionLoadValue>]': 0, 1ts(2345)
```

To solve that, I'm just doing:

```ts
const useValue = () => {
  const [state, dispatch] = useReducerAsync<
    Reducer<State, Action>,
    AsyncAction,
    AsyncAction
  >(reducer, initialState, asyncActionHandlers);
  return [state, dispatch] as [State, Dispatch<AsyncAction>];
};
```

So it looks like some TS error and nothing related to your library but I might be wrong. Any ideas?

**2. If I use `useReducerAsync` in the `useValue` then `useUpdate` only expects async actions**

I'm using async actions according to the examples in docs and when I do:

```ts
import { useCallback } from "react";
import { useDispatch } from "./store";

export const Button: React.FC = () => {
  const dispatch = useDispatch(); // useDispatch is an alias for useUpdate.

  const handleClick = useCallback(() => {
    dispatch({ type: "LOAD_VALUE_WAIT", wait: 200 });
  }, [dispatch]);

  return <button onClick={handleClick}>Load</button>;
};
```

then the `dispatch` method only expects me to invoke it with `AsyncAction`:

```ts
const dispatch: (value: AsyncAction) => void
```

**3. Add more info about types and why they are being used**

I don't know what's the point of having `OuterAction` type. Is there any reason beside distinguishing between actions being called from async actions?

If I do:

```ts
useReducerAsync<
    Reducer<State, Action>,
    AsyncAction,
    AsyncAction | OuterAction
  >(reducer, initialState, asyncActionHandlers);
```

then I can only use `OuterAction`s in the async actions so I had to change type from `AsyncAction | OuterAction` to `AsyncAction | Action`. Overall, the types used here are not described anywhere and it's hard to tell where should go what to properly type project.

**Comment by dai-shi** [comment]
Hey, thanks for the feedback.

1.

```ts
return [state, dispatch] as [State, Dispatch<AsyncAction>];
```
This is correct. Without `as`, TS infers the type as an array instead of a tuple.
The other way is this.
```ts
return [state, dispatch] as const;
```
I prefer this one, but it requires newer (not the newest) version of TS.

2. 

```ts
  const [state, dispatch] = useReducerAsync<
    Reducer<State, Action>,
    AsyncAction,
    AsyncAction | Action
  >(reducer, initialState, asyncActionHandlers);
```

Your code is like this. It means the type of dispatch is `Dispatch<AsyncAction | Action>`.
This works as you expect, right?
(I assume you didn't have ` | Action` for the first time.)

3.

Yeah, I'd admit the documentation needs to be improved.
The reason I split InnerAction and OuterAction is to limit the action type for the exported dispatch.
Oh, I just noticed the inconsistency between the type definition in use-reducer-async
and the tutorial https://react-tracked.js.org/docs/tutorial-04.
Maybe, that confused you.

InnerAction: used only by async handlers
OuterAction: used from everywhere
AsyncAction: handled by async handers
ExportAction: used by exported dispatch

So, Reducer Action = InnerAction | OuterAction
and, exported Action = AsyncAction | OuterAction

I will fix the inconsistency and try to add some more description in https://github.com/dai-shi/use-reducer-async.

The tutorial  https://react-tracked.js.org/docs/tutorial-04 is not only for TS users, so I'm not sure how to improve it... any suggestions? I think I will simplify the example to mitigate confusion.

**Comment by dai-shi** [comment]
Just updated:
- use-reducer-async https://www.npmjs.com/package/use-reducer-async/v/0.6.0
- tutorial-04 https://react-tracked.js.org/docs/tutorial-04/

I hope it less confuses you with TS typing.

**Comment by lukejagodzinski** [comment]
1. Oh right tuple type. It makes sense, I've read about that some time ago but forgot that it applies here :). Ok so I will use a new TypeScript's `const`.

2. The code example that I've used is making TS complain:
```ts
  const [state, dispatch] = useReducerAsync<
    Reducer<State, Action>,
    AsyncAction,
    AsyncAction | Action
  >(reducer, initialState, asyncActionHandlers);
```

and in the component if I do:

```ts
dispatch({ type: "SET_LOADING", loading: false });
```

it says:

```
(property) type: "SET_LOADING"
Type '"SET_LOADING"' is not assignable to type '"LOAD_VALUE_WAIT" | "LOAD_VALUE"'.ts(2322)
store.tsx(17, 3): The expected type comes from property 'type' which is declared here on type 'AsyncAction'
```

To demonstrate it I've updated `Button.tsx` file in this reproduction https://codesandbox.io/s/sad-meadow-tcwzt

3. Hmm now I'm even more confused :), you're mentioning even more types now :P
I have to digest what you wrote and see updated examples.

3a.
> InnerAction: used only by async handlers

Don't you mean **sync handles**, not **async handlers**? Those can be used inside the `store.ts` file, right?

3b.
> OuterAction: used from everywhere

So this one can be used outside of the `store.ts`, file? For example in components, right?

3c.
> AsyncAction: handled by async handers

Make sense

3d.
> ExportAction: used by exported dispatch

I see this name for the first time. Is it some internal type of the library? Is this type being used when I export `useUpdate: useDispatch` from the `store.ts` file and it will use this type when I write:

```ts
const dispatch = useDispatch();
dispatch({ type: "some ExportAction here, right?" });
```

**Comment by lukejagodzinski** [comment]
I've just copied code from the tutorial into codesandbox and everything seems to work, so problem is somewhere in my code. It's just hard to deal with so many types. I will post an answer here when I found bug. Maybe it will be some clue for others to put in docs. And I just followed documentation when I wrote my code, so that might happen to someone else

**Comment by dai-shi** [comment]
> Hmm now I'm even more confused :), you're mentioning even more types now :P

Oops, sorry about that. With use-reducer-async v0.6.0, ExportAction = AsyncAction | ReducerAction<R> by default, so you don't need to specify it. I mean, one doesn't need to understand InnerAction/OuterAction/ExportAction at the beginning. They are for stricter typing.

> I should write:
> `return [state, dispatch] as [State, Dispatch<AsyncAction | Action>];`

Oh!! You are right. I missed that. `as const` also solves the issue, correct?

> But it wasn't obvious as types are complicated here

I agree. I'm not sure if there's anything we can do on the library end.

**Comment by lukejagodzinski** [comment]
> Oops, sorry about that. With use-reducer-async v0.6.0, ExportAction = AsyncAction | ReducerAction<R> by default, so you don't need to specify it. I mean, one doesn't need to understand InnerAction/OuterAction/ExportAction at the beginning. They are for stricter typing for TS experts.

Ok makes sense :) Probably will understand it better, the more I work with it.

> Oh!! You are right. I missed that. as const also solves the issue, correct?

It didn't work in the CodeSanbox but probably they are using older TS version. I haven't tried yet in my project as I'm in the middle of refactoring and later will get back to rewriting Redux code in ReactTracked

> I agree. I'm not sure if there's anything we can do on the library end.

As I said, I'm not TS expert but couldn't types be inferred from what we pass as the arguments of the `useReducerAsync` function?

**Comment by dai-shi** [comment]
As for `as const`, it was my misunderstanding.
I tried your codesandbox and the error says `readonly` is not assignable.
So, you are right. `as const` doesn't work now. It's not about the TS version.
I will investigate if there's anything I can do with `createContainer` type.

I'm not so expert in TS, and what I mean in the previous comment is that TS error messages are often not very obvious which we can hardly help. All I can do is probably to name types in a meaningful way in the library.

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/react-tracked/v/1.0.2
v1.0.2 should fix the "as const" issue.

**Comment by lukejagodzinski** [comment]
> https://www.npmjs.com/package/react-tracked/v/1.0.2
v1.0.2 should fix the "as const" issue.

Yep, it works now with `as const` thanks! :)

Btw. I want to really thank you for quick replies. You're really doing amazing work. I know how hard is it to maintain open-source library, so kudos to you :)

**Comment by lukejagodzinski** [comment]
Hmm actually I've noticed that I can omit types and it still works perfectly fine with all the intellisense:

```ts
const [state, dispatch] = useReducerAsync(reducer, initialState, asyncActionHandlers);
```

**Comment by dai-shi** [comment]
You are welcome!

Yes, you can omit types for useReducerAsync because all arguments to it is properly typed.

**Comment by lukejagodzinski** [comment]
Ok, I will close this issue now. Thanks!
