### ISSUE TITLE
Calling async actions from other async actions

### ISSUE THREAD

**Issue by lukejagodzinski** [dai-shi/react-tracked#37]
Hey, as in the subject. Is it possible to call async action from within other async action?

In Redux + Redux Thunk, it's possible to do something like:

```ts
export const asyncAction = (args: Args): ThunkResult<void> => async (
  dispatch,
  getState
) => {
  try {
    await dispatch(anotherAsyncAction());
  } catch (error) {
    /* ... */
  }
};
```

But it doesn't seem to be possible in ReactTracked. Is it?

**Comment by dai-shi** [comment]
Yeah, it's not like redux-thunk in that sense.

What you could do now is:
```js
const asyncActionHandlers = {
  SLEEP: (dispatch, getState) => async (action) => {
    dispatch({ type: 'START_SLEEP' });
    await new Promise(r => setTimeout(r, action.ms));
    dispatch({ type: 'END_SLEEP' });
  },
  FOO: (dispatch, getState) => async (action) => {
    // ...
    await asyncActionHandlers.SLEEP(dispatch, getState)({ type: 'SLEEP' });
    // ...
  },
};
```

BTW, I assume this is a question regarding `use-reducer-async`.
You could try [use-saga-reducer](https://github.com/azmenak/use-saga-reducer) if you are familiar with sagas, which might be more powerful.

I haven't tried but there's also [react-hook-thunk-reducer](https://github.com/nathanbuchar/react-hook-thunk-reducer).

**Comment by lukejagodzinski** [comment]
Yep, sorry I should rather ask this question in the `use-reducer-async` repository.
So you mean that if I use different reducer (`react-hook-thunk-reducer`) that I might be able to do it the Thunk way?
Haven't you thought about allowing that or actually come with some nicer API for doing so? TBH, I don't like how it's done in ReduxThunk as it's not clear at first glance if I'm executing sync or async action. I would prefer to have something like `dispatch` for sync actions and `dispatchAsync` for async actions. Also TS types would be probably easier to do. I have hard time working with TS types in ReduxThunk.
I would just like to know if you have any plans to work on it :)

And, to your code example. Yes I was doing it this way but it looks a little bit hacky imho :)

**Comment by dai-shi** [comment]
To be honest, I didn't look into react-hook-thunk-reducer in detail, but I would avoid using it.
The thunk abstraction doesn't seem good in React world.

I would either recommend use-reducer-async, or if you want more, create your own custom hook.

> I have hard time working with TS types in ReduxThunk.

That's one of the reasons I'd avoid redux-thunk.

> I would just like to know if you have any plans to work on it :)

Would be glad if you gave me more concrete example.
At the moment, I'm not sure what is a problem a library should solve.

> it looks a little bit hacky imho

It might be only about how you structure your code.

```js
const sleep = async (dispatch, ms) => {
  dispatch({ type: 'SLEEP_STARTED' });
  await new Promise(r => setTimeout(r, ms));
  dispatch({ type: 'SLEEP_FINISHED' });
};

const foo = async (dispatch, arg1) => {
  dispatch(...);
  await ...;
  await sleep(dispatch, 1000);
};

const asyncActionHandlers = {
  SLEEP: dispatch => action => sleep(dispatch, action.ms),
  FOO: dispatch => action => foo(disptch, action.arg1),
};
```

----

> Yep, sorry I should rather ask this question in the use-reducer-async repository.

It depends. It's actually OK, because you are asking the use case in React Tracked.

**Comment by dai-shi** [comment]
Still having any issues?

**Comment by lukejagodzinski** [comment]
@dai-shi hey, sorry had to postpone moving to react-tracked as other things are more important but yeah I will use your approach. Actually I wanted to avoid that but it will just be a little bit more rewrite but code will still be clean and readable. Thanks! :) Will close this issue
