### ISSUE TITLE
My games will not be refreshed like i need

### ISSUE THREAD

**Issue by ppprevost** [dai-shi/react-tracked#38]
Hello Daishi Kato,

Thank you for your support to the React community.

I just tried a new branch on my website because i wanted to optimise my videogame : 
https://github.com/ppprevost/jeu-cv-react/tree/react-tracked

When i install it, it will be very disapointing, there is many bugs ! Could you help me to understand why ?
PP

**Comment by dai-shi** [comment]
Hi!
What is the error message?
I would be happy to help. It would be easier if the question was small, or step by step.

**Comment by dai-shi** [comment]
Closing as stale.
