### ISSUE TITLE
Is there any problem on example?

### ISSUE THREAD

**Issue by ezranbayantemur** [dai-shi/react-tracked#55]
Hello @dai-shi . Firstly thanks for the repo. 
I have problem about example on the README. I try to implement it on my React Native project but it looks like doesn't block the unnecessary render.

Here is my code (same as your's, just with native components):
```javascript
import React, { useReducer } from 'react';
import { createContainer } from 'react-tracked';
import { TextInput, View, Text, Button, SafeAreaView } from 'react-native';

const useValue = ({ reducer, initialState }) => useReducer(reducer, initialState);
const { Provider, useTracked } = createContainer(useValue);

const initialState = {
    count: 0,
    text: 'hello',
};

const reducer = (state, action) => {
    switch (action.type) {
        case 'increment': return { ...state, count: state.count + 1 };
        case 'decrement': return { ...state, count: state.count - 1 };
        case 'setText': return { ...state, text: action.text };
        default: throw new Error(`unknown action type: ${action.type}`);
    }
};

const Counter = () => {
    const [state, dispatch] = useTracked();
    console.log("RENDER COUNTER");
    return (
        <View>
            <Text>{Math.random()}</Text>
            <View>
                <Text>Count: {state.count}</Text>
                <Button title="+1" onPress={() => dispatch({ type: 'increment' })} />
                <Button title="-1" onPress={() => dispatch({ type: 'decrement' })} />
            </View>
        </View>
    );
};

const TextBox = () => {
    const [state, dispatch] = useTracked();
    console.log("RENDER BOX");
    return (
        <View>
            <Text>{Math.random()}</Text>
            <View>
                <Text>Text: {state.text}</Text>
                <TextInput value={state.text} onChangeText={event => dispatch({ type: 'setText', text: event })} />
            </View>
        </View>
    );
};

const App = () => (
    <Provider reducer={reducer} initialState={initialState}>
        <SafeAreaView>
            <Text>Counter</Text>
            <Counter />
            <Counter />
            <Text>TextBox</Text>
            <TextBox />
            <TextBox />
        </SafeAreaView>
    </Provider>
);

export default App
``` 

My output: 
![Simulator Screen Shot - iPhone 11 - 2020-07-06 at 17 29 01](https://user-images.githubusercontent.com/42299721/86604566-36091100-bfae-11ea-9f65-ff4de07f691d.png)

When I click the counter button it's renders TextBox component too.
![Screen Shot 2020-07-06 at 17 29 39](https://user-images.githubusercontent.com/42299721/86604711-6781dc80-bfae-11ea-9e16-b5b0432893ad.png)

I believe it shouldn't render the other component. Am I wrong? Or is there any misuse?

**Comment by dai-shi** [comment]
Hey, thanks for trying out.

It's probably related with the (long) discussion in #52 

In short,
- v1.2 would work as you expect, however,
- v1.3 and v1.4 is a bit modified for Concurrent Mode, and
- v2-alpha will probably behave better in the future.
- If console.log is wrapped in useEffect, it will show more intuitive result.

If you are curious about the behavior, trying v1.2.0 would help understanding it.
You are welcome to ask further questions.

(and I feel like I should write something down in README.)

**Comment by ezranbayantemur** [comment]
Thank you so much for the quick response. I'll be waiting for it 👍

**Comment by dai-shi** [comment]
Note that I did run one benchmark https://github.com/dai-shi/react-tracked/issues/50#issuecomment-633746421 which shows v1.4 works as good as v1.2.
Currently, I think it's safe and reasonable to use v1.4.

Closing this, but feel free to add more comments.
