### ISSUE TITLE
[Communication post] compare with concent

### ISSUE THREAD

**Issue by fantasticsoul** [dai-shi/react-tracked#67]
Hey, dude, I know react-tracked from bestofjs, and I really like your idea, what do you think of [concent](https://github.com/concentjs/concent), it is also based on proxy feature.

If you are afraid of its bundle size(26kb), Here is a very very minimal concent prototype online show case( it will grow to be concent-lite in the feature)
https://codesandbox.io/s/mini-concent-n1t0t?file=/src/App.js

**Comment by dai-shi** [comment]
Hi, from the csb example, it looks to me like zustand + some patterns.
So, `state` is wrapped by a proxy and property access is tracked. In that sense, it's similar to react-tracked, or reactive-react-redux. hookstate also uses proxies (at least when I saw one of original versions.) There might be some other libs using proxies. Good to know concent is also utilizing proxies.

**Comment by fantasticsoul** [comment]
Yes, the funny thing (I don't know if you noticed) in concent is that user **do not need wrap** a `provider` in the root react node, so it is very easy to use in your existing project.

```js
run({
  // configure some models
  oneModel:{
    state: { num:1, age: 12  },
  }
})

function Comp(){
   const { state, setState } =useConcent('oneModel');
   // state is a proxy object, for helping concent collect render dependency in every render period
   // setState can trigger all the react ins that belong to oneModel module and read the committed state
}
```

Sharing state is so easy for user, and exact update is also become very easy for the state management lib^_^

**Comment by dai-shi** [comment]
Yes, I noticed it. That's why I thought it's similar to zustand.
It's not funny at all. We don't need React context at all for external module state.
My reactive-react-redux v5 also doesn't depend on contexts as redux is an external store.
If you are interested in connecting module state and react, you want to check useSubscription and experimental useMutableSource.

**Comment by fantasticsoul** [comment]
ok, thanks, I will try

**Comment by dai-shi** [comment]
No worries, I get it correctly.

**Comment by dai-shi** [comment]
Closing this, but feel free to continue discussions in this issue.
