### ISSUE TITLE
Keeping React-Tracked Fast

### ISSUE THREAD

**Issue by ammarahm-ed** [dai-shi/react-tracked#74]
I have been using this library for over a year, I have a simple question that I would like to know about.

Is it alright to store large objects/(arrays of complex objects) in the state and does it effect the performance of dispatch? Let's say that I have the following state:
```js
const defaultState = {
userLoggedIn:false, 
userPosts:[] // Array of post objects
}
```
If I am only updating userLoggedIn value in dispatch, will the dispatch function take more time to run if the size of userPosts is large?

**Comment by dai-shi** [comment]
No, it should be just fine. Your assumption on dispatch behavior is correct.
In addition, unless you don't read `userPosts` in render with `useTrackedState()`, it doesn't even know how big the object/array is.

BTW, we have a discord server (the invitation link is in README) and you could also ask questions there. GitHub issues is totally fine though.

**Comment by ammarahm-ed** [comment]
Okay! Thanks for the answer and I will definitely join the discord for any future queries
