### ISSUE TITLE
New memo ignores prop definitions

### ISSUE THREAD

**Issue by G07cha** [dai-shi/react-tracked#75]
I've noticed that with move to typescript while losing `memo` from react-tracked props types are not being passed through unless they are specified in callback arguments itself. I've tried fixing it myself but wasn't able to unfortunately, hence made this issue.

```ts
// Works
const MyComponent = memo(({ foo }: { foo: string }) => {})

// Doesn't, typeof foo is 'any'
const MyComponent: FC<{ foo: string }> = memo(({ foo }) => {})
```

Here is another example in sandbox:

![Schermafbeelding 2021-01-14 om 13 14 58](https://user-images.githubusercontent.com/6943514/104589700-8e5e5100-566a-11eb-948f-de5356d1aa16.png)

You can try it out here: https://codesandbox.io/s/friendly-rhodes-n8rm8?file=/src/components/FilterLink.tsx

**Comment by dai-shi** [comment]
Ah, I see, but does it work well if it's `React.memo`?

**Comment by G07cha** [comment]
@dai-shi yes, it's hard to wrap my head around this but it appears to work because of props being passed through generics and inheriting them from the target type. I've noticed that I haven't saved my codesandbox example initially, it should now accurately represent the described issue.
