### ISSUE TITLE
Memo doesn't work with forwarded ref

### ISSUE THREAD

**Issue by LeoLeBras** [dai-shi/react-tracked#78]
Hello and thank you for all this work! 🤗

When using the memo function (from `react-tracked`) with a component using `React.forwardRef`, I encounter several errors:

```
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

By changing the code in this way, everything works again ⬇️ 

```ts
export function memo(
  Component: any,
  propsAreEqual?: any,
) {
  const WrappedComponent = forwardRef((props: any, ref: any) => {
    Object.values(props).forEach(trackMemo);
    return createElement(Component, { ...props, ref );
  });
  return reactMemo(WrappedComponent, propsAreEqual);
}
```

Have you ever encountered this kind of error? I can open a PR if you want!

Greetings from Paris 🇫🇷.

**Comment by dai-shi** [comment]
Oh, nice catch.
I didn't notice as I don't usually use `ref`.
Please go ahead and file a PR.
I don't know enough about the proper combination of forwardRef and createElement, but maybe ok.
