### ISSUE TITLE
ToDo App (useState+Immer) Error: 'get' on proxy: property '0' is a read-only and non-configurable data property

### ISSUE THREAD

**Issue by chicus12** [dai-shi/react-tracked#79]
Hello and thank you for this amazing work!

I'm trying to understand and use this amazing lib, one thing that I did was clone the sandbox example of ToDo App (useState+Immer) and update the version of immer to 8.0.0 but I just got this error:

![image](https://user-images.githubusercontent.com/5809258/104799197-bb0d8800-5792-11eb-91e6-01424f171941.png)

Do you know how I can fix it?

Thank you in advance!

**Comment by dai-shi** [comment]
That error could be seen with some non plain objects. Is it from the new immer?
Can you share reproducible codesandbox?

If we know the exact issue, we could either fix it or describe as a limitation.

Thanks!

**Comment by wisammechano** [comment]
I am having the same issue with an array. here is a [code sandbox](https://codesandbox.io/s/react-cart-context-test-k8t0s)

**Comment by dai-shi** [comment]
@wisammechano Hey, thanks for the codesandbox.

https://codesandbox.io/s/react-cart-context-test-k8t0s

Hm, I'm still not sure how to reproduce the error. Can help to instruct please?

**Comment by chicus12** [comment]
Hi @dai-shi look at this:

https://codesandbox.io/s/boring-leftpad-ccex0

It's the same code of https://react-tracked.js.org/docs/tutorial-03 but with the immer v8.0.0 the last version available and react-tracked v1.6.2.

Get the error just for run the example.

**Comment by dai-shi** [comment]
@chicus12 
Thanks. I can repro.
This is due to the breaking change in v8. https://github.com/immerjs/immer/releases/tag/v8.0.0
If I disable the freezing, it seems to work.
https://codesandbox.io/s/blazing-meadow-k4j5t

Now, frozen objects are expected use cases, and are somewhat dealt with.
This is probably an edge (but normal) case with array prototype functions.
I will investigate it. Not sure how difficult it is to solve this.

**Comment by eli-s-r** [comment]
@dai-shi I'm still getting this issue on the latest versions:
```
'get' on proxy: property '0' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '#<Object>')
```
`setAutoFreeze(false)` does fix this, but should this still be necessary?

**Comment by dai-shi** [comment]
https://codesandbox.io/s/wizardly-sea-stqpl This seems working.

Would you please create a minimal reproduction with codesandbox and file a new issue?

**Comment by theskinnycoder** [comment]
> @dai-shi I'm still getting this issue on the latest versions:
> 
> ```
> 'get' on proxy: property '0' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '#<Object>')
> ```
> 
> `setAutoFreeze(false)` does fix this, but should this still be necessary?

Me too! I have many react tracked stores, and I had to call `setAutoFreeze(false)` everywhere I used `createContainer`
