### ISSUE TITLE
Discussion: how to plugin a new feature like middleware

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/react-tracked#8]
react-tracked doesn't have a plugin system like reactive-react-redux which can use redux middleware system.

We shouldn't reinvent redux middleware like system. react-tracked should stick with react contexts.
React hooks oriented solution would be something like function composition instead of middleware system.

A naive idea: As we have createContainer, can we utilize it?

```javascript
// pattern1
const container = extendContainer(createContainer(useValue));

// pattern2
const container = enhance(createContainer)(useValue);
```

**Comment by dai-shi** [comment]
Mentioning @chrisrzhou as you expressed some interests in it.

**Comment by dai-shi** [comment]
There's various recipes now: https://github.com/dai-shi/react-tracked/blob/1abd111b1572b7059188ebad66f3dbe9dd334ddd/website/docs/recipes.md
Some of those can be implemented as middleware.

**Comment by ckeeney** [comment]
I'm interested in setting up a middleware similiar to [`redux-persist`](https://github.com/rt2zz/redux-persist) or [`storeon-localstorage`](https://github.com/storeon/localstorage).  Is insude my `useValue` hook the place to setup loading and persistence of state?

**Comment by dai-shi** [comment]
@ckeeney Yeah, I think `useValue` is a place to setup for the persistence.
react-tracked is a bit different from redux or storeon that have external stores.
react-tracked doesn't have any external store, and it works like normal hooks. So, any existing approach to add persistence to `useState` would work.
Would you give it a try? I can help. Or, I can try creating one if you need something to play with.

**Comment by dai-shi** [comment]
I mean I would like to add a recipe in https://react-tracked.js.org/docs/recipes, once we created one.

**Comment by ckeeney** [comment]
I'm using `useReducer` which makes things a little bit more complicated.  I'd like to load the state from the [`init` argument](https://reactjs.org/docs/hooks-reference.html#lazy-initialization).

I'm using [`localforage` which has an async API](https://github.com/localForage/localForage#callbacks-vs-promises), and I couldn't make the async stuff work in the `init` argument.

As an alternative I tried loading the data in `useValue` and dispatching an `INIT ` action to update the state (since we don't have a `setState` with `useReducer`).  This is almost working.  I can see the data properly getting written when the state changes.  However, when I refresh the page the default state overwrites whatever was in client storage.  

Here is the code I have.  Sorry, it's still very rough.

source code for `useClientStorage` is [here](https://github.com/nonnontrivial/use-localforage/issues/1#issuecomment-543846425).

```js
import React, {useReducer, useEffect, useState} from 'react';
import { createContainer } from 'react-tracked';
import {modalReducer} from "./modals";
import {combineReducers} from "redux";
import {todosReducer} from "./todos";
import {useClientStorage} from "../hooks/use-clientstorage";
import { createAction, handleActions, combineActions } from 'redux-actions';
import {mergeDeepRight, equals} from "ramda";

const initAction = createAction('INIT');
const metaReducer = handleActions({
    initAction: mergeDeepRight
}, {loaded: false});

const reducer = combineReducers({
    modal: modalReducer,
    todos: todosReducer,
    meta: metaReducer
});

const useValue = () => {
    const [data, setData, isLoading, err] = useClientStorage('persistedState');

    // our reducers return default states on undefined state and empty action.
    const defaultState = reducer(undefined, {});

    const [state, dispatch] =  useReducer(reducer, defaultState);


    useEffect(() => {
        console.log('in use effect');
        if (! isLoading) {
            console.log('dispatching!');
            console.log({data, setData, isLoading, err});
            dispatch(initAction(data))
        }
    }, [isLoading, data])
    useEffect(() => {
        if (! isLoading && !equals(state, defaultState) ) {
            setData(state)
        }
    }, [state, isLoading])
    return [state, dispatch];
};

const container = createContainer(useValue);

export const {
    Provider: SharedStateProvider,
    useTrackedState,
    useUpdate: useDispatch,
} = container;

```

**Comment by dai-shi** [comment]
> using useReducer which makes things a little bit more complicated.

Yeah. It should still be possible if you have a control on reducer.

> localforage which has an async API, 

The async API sounds hard. Let me start with sync localStorage and see how we can extend it.

```js
const reducer = ...;
const initialState = ...; // used only if localStorage is empty.
const useValue = () => {
  const init = () => {
    const preloadedState =  JSON.parse(localStorage.getItem('persistedState'));
    // maybe should validate preloadedState
    return preloadedState || initialState;
  };
  const [state, dispatch] = useReducer(reducer, null, init);
  useEffect(() => {
    localStorage.setItem('persistedState', JSON.stringify(state));
  }, [state]);
  return [state];
};
```

Now, let's make it async.

```js
const reducer = ...;
const initialState = ...;
const useValue = () => {
  const init = () => {
  const [state, dispatch] = useReducer(reducer, initialState);
  const loaded = useRef(false);
  useEffect(() => {
    (async () => {
      dispatch({ type: 'PRELOAD_STARTED' });
      const serialized = await localforage.getItem('persistedState');
      const preloadedState = JSON.parse(serialized);
      // maybe validation
      dispatch({ type: 'PRELOAD_FINISHED', preloadedState });
      loaded.current = true;
    })();
  }, []);
  useEffect(() => {
    if (loaded.current) {
      localforage.setItem('persistedState', JSON.stringify(state));
    }
  }, [state]);
  return [state];
};
```

@ckeeney How does it look like?

**Comment by ckeeney** [comment]
@dai-shi thanks for pointing me in the right direction.  The sync API example you built worked almost as expected.  I believe `useValue` should also return an update function (either `setState` or `dispatch`) so I added that.  I also used `window.localStorage` because I was getting an error otherwise (next.js).

Here is the **sync** example with those fixes:

```js
const init = () => {
    if (typeof window === 'undefined') {
        return defaultState
    }
    const preloadedState =  JSON.parse(window.localStorage.getItem(myStorageKey));
    // maybe should validate preloadedState
    return preloadedState || defaultState;
}

const useValueSync = () => {
    const [state, dispatch] = useReducer(reducer, defaultState, init);
    useEffect(() => {
        window.localStorage.setItem(myStorageKey, JSON.stringify(state));
    }, [state]);
    return [state, dispatch];
};

```

Your async example needed some work, but definitely set me off in the right direction. It looks like you've edited it since I last looked at it.  Here is the version I came up with based on one of your edits of your async example:

```js
const useValueAsync = () => {

    const persistableReducer = reduceReducers(defaultState, reducer, loadPersistedDataReducer);
    const [state, dispatch] =  useReducer(persistableReducer, defaultState, undefined);
    const loaded = useRef(false);

    const loadData = async () => {
        dispatch(preloadStarted());
        const serialized = await localforage.getItem(myStorageKey);
        const preloadedState = JSON.parse(serialized);
        const persistedState = omit(['meta'], preloadedState);

        // maybe validation
        dispatch(preloadFinished(persistedState));
        loaded.current = true;
    };

    useEffect(() => {
        loadData();
    }, [])
    useEffect(() => {
        if (loaded.current) {
            // remove things you don't want persisted from state.
            const persistedState = omit(['meta'], state);
            localforage.setItem(myStorageKey, JSON.stringify(persistedState));
        }
    }, [state]);
    return [state, dispatch];
};
```

And here are my relevant reducer and actions.  The `metaReducer` adds a `meta` key to state to tell components about loading state to block rendering until client storage is loaded (is there a better way to do this?).  This key is removed before saving and before restoring state.

The `loadPersistedDataReducer` merges the current state with whatever the persisted state is using `ramda`'s `mergeDeepRight`.

```js
import React, {useEffect, useRef, useReducer} from 'react';
import { createContainer } from 'react-tracked';
import {combineReducers} from "redux";
import localforage from 'localforage';
import { createActions, handleActions } from 'redux-actions';
import {mergeDeepRight, omit} from "ramda";
import reduceReducers from 'reduce-reducers';

const {preloadStarted, preloadFinished} = createActions({}, 'PRELOAD_STARTED', 'PRELOAD_FINISHED');

const metaReducer = handleActions({
    [preloadFinished]: (state) => ({...state, loaded: true, loading: false}),
    [preloadStarted]: (state, action) => ({...state, loading: true})
}, {loaded: false, loading: false});

const loadPersistedDataReducer = handleActions({
    [preloadFinished]: (state, {payload}) => mergeDeepRight(state, payload),
}, {});


const reducer = combineReducers({
    modal: modalReducer,
    todos: todosReducer,
    meta: metaReducer,
});


const defaultState = reducer(undefined, {}); // our reducers return default states on undefined state and empty action.
const myStorageKey = 'myStorageKey'

```

**Comment by dai-shi** [comment]
@ckeeney Wonderful!

I will put the sync version in the recipes section.

Would you mind if I ask you to put the async version in GitHub wiki?
If you are willing to do it, I will set up the wiki.
One minor improvement is that since you now have `state.meta.loaded`, I guess you can use it instead of `loaded.current`.

**Comment by ckeeney** [comment]
@dai-shi how do I do that?  I clicked the wiki button but it takes me back to the repo homepage.

**Comment by dai-shi** [comment]
@ckeeney Hi, I just changed the settings. Please try it again.

**Comment by dai-shi** [comment]
Note: The example with async actions is in https://react-tracked.js.org/docs/tutorial-04.

**Comment by dai-shi** [comment]
Closing this as stale.
