### ISSUE TITLE
Extra re-renders with useTracked question

### ISSUE THREAD

**Issue by pawelhoros** [dai-shi/react-tracked#83]
I'm testing some state management options for Next.js project, and usually context+tracked is more than enough in my CRA apps. 
Sadly it does not work with Next.js. All state based components are updated on any state change just like it would be clean react context only.

It's more like a question is it possible at all to make this work together or what I'm missing?

**Comment by dai-shi** [comment]
hm, that sounds like unexpected behavior. is it SSR?
Would you be able to create a small example that shows this behavior, so I can investigate it?

**Comment by pawelhoros** [comment]
https://github.com/pawelhoros/next-tracked-test

Just as I did this example I found out that it's something else, it doesn't relate to Next.js.

When there is no state used in page component (parent), it works fine. But when there is useTracked hook, it triggers to rerender all children components. I should probably go out to SO to ask this question :) 
Fell free to delete it.

**Comment by dai-shi** [comment]
If it's still related with react-tracked, here is fine. (If it's a react question in general, SO would be better.)
If it's not related to nextjs, can you reproduce it with codesandbox?

**Comment by pawelhoros** [comment]
https://codesandbox.io/s/wandering-architecture-49lkd

It works same as above example.

**Comment by dai-shi** [comment]
Gotcha. Thanks for the repro.

This works by design.

So,
```js
const [state, dispatch] = useTracked();
```
without using `state` in the component means it's interested in the `state` object as a whole.
So, useTracked triggers re-render every time `state` is changed.
Here's the fixed version:
https://codesandbox.io/s/old-shape-ld521?file=/src/App.js

---
I'd see this as a doc issue, but not quite sure how to improve..

**Comment by pawelhoros** [comment]
Thank you, it's all clear.
