### ISSUE TITLE
react-tracked failed in case if don't give initial props? (any bypass ?)

### ISSUE THREAD

**Issue by sahilrajput03** [dai-shi/react-tracked#84]
I tried to set state which is not set in initital value and surpisingly it doesn't trigger render for my 
Counter component which uses the same property. So does this imply that any property i am supposed to change must be there in initial value ..? This could be huge pain..

```js
const Counter = () => {
  const [state, setState] = useSharedState();
  const increment = () => {
    setState((prev) => ({...prev, count: prev.count || 22 + 1}));
  };
  useUpdateRerenderLog('Counter');
  return (
    <div>
      {Math.random()}------
      {state.count}
      <button onClick={increment}>+1</button>
    </div>
  );
};
//Clickinig the increment button doesn't work after first click ...., can that be fixed without putting the initial value before hand ..?
const initialState = {};

const useMyState = () => useState(initialState);

export const {
  Provider: SharedStateProvider,
  useTracked: useSharedState
} = createContainer(useMyState);

```

Check it out @ https://codesandbox.io/s/failed-react-tracked-otx9o?file=/src/Counter.js

**Comment by sahilrajput03** [comment]
Omg, my javascript logics are very not well, I figured the bug..

```
  const increment = () => {
    setState((prev) => ({...prev, count: (prev.count || 22) + 1}));
  };

```

**Comment by sahilrajput03** [comment]
@dai-shi , you have made it really well designed..!!
Do you yourself see any missing thing react-tracked... ? Just curious to know..  :rofl: ...

**Comment by dai-shi** [comment]
> Do you yourself see any missing thing react-tracked... ?

It should be good as is. There could still be some unknown bugs/behaviors around proxies, though. And `React.memo` is tricky (react-tracked ended up providing custom `memo`.)

The proxy part is implemented as a separate library `proxy-compare`, which is now used in valtio and proxy-memoize.

**Comment by sahilrajput03** [comment]
Thats really good!!
Thanks for answering @dai-shi , :100: :)

*For some reasom my I don't get my github notifications everytime.
