### ISSUE TITLE
component extra re-render when other state changes

### ISSUE THREAD

**Issue by Nassimadebeo** [dai-shi/react-tracked#86]
I just discovered this library witch i found great !

### Problem: 
when i use version 0.11.0 , everything work, but the behavior is different using the latest stable version 1.6.5

### The difference is:
 all components extra re-render even if they track only on some state, witch is weird

i even tested this on the react tracked **todo list** example codesandbox.
https://codesandbox.io/s/purple-sun-xte3v

**Comment by dai-shi** [comment]
Hi, thanks for tuning in.
I know what you mean. This is a workaround in use-context-selector `useContextUpdate`, which will improve a behavior in concurrent mode. I know it's not ideal, but it works.
We have an option to drop the support of CM, or make it opt-out, or opt-in. But, it would require extra explanation and understanding, which is not super nice.

The rational is render function has to be "pure" and console.log is side effect.
If you put console.log in useEffect, you wouldn't be surprised with the behavior.
https://codesandbox.io/s/confident-cray-etoqs

**Comment by Nassimadebeo** [comment]
@dai-shi thanks for the quick answer. understood for me !. and by the way, thanks for thinking into building such a useful module, it solves the react context cos.
