### ISSUE TITLE
Re-rendering components on any change with Preact

### ISSUE THREAD

**Issue by fnpen** [dai-shi/react-tracked#90]
I am changing the `time` property in the state using interval each second, I expect to see re-render only for a component that uses this property, and it works as expected on React,
In the case of Preact, all components rerender which use useTrackedState.

### React Example

![React](https://raw.githubusercontent.com/fnpen/react-tracked-preact-todo-problem/master/react-demo.gif)

### vs Preact Example

![Preact](https://raw.githubusercontent.com/fnpen/react-tracked-preact-todo-problem/master/preact-demo.gif)

The codesandbox does not support aliases with webpack to prepare preact example.
I prepared a repository with this example: https://github.com/fnpen/react-tracked-preact-todo-problem
It uses Webpack 5(cra+eject+edited). Webpack 4 does not support the 'boolean' value for aliases.

I'm switching between React and Preact by commenting in webpack.config.js: 

```
"react": "preact/compat",
"react-dom": "preact/compat",
"scheduler": false, // it's not available in Preact, and you made the special fix in use-context-selector
```

I hope it helps to find the solution, and thank you for the awesome package.

**Comment by dai-shi** [comment]
Thanks for trying. To be honest, I'm not really sure how this is happening at this moment.

It seems related with https://github.com/dai-shi/use-context-selector/pull/36, but that should be fixed already. There might be some other behavioral difference.

If you can spend time on this without knowing if this is solvable, what I'd like you to try is:
a) to see if the problem persists with use-context-selector without react-tracked.
b) and, to shrink down the example further to make a minimal reproduction.

I know your example now is already small one. And, I could fix it if I understood what's happening with it.

**Comment by fnpen** [comment]
Thank you,

I check and use-context-selector@1.3.7, I will look on 'use-context-selector' only example.
