### ISSUE TITLE
No access to either property of the proxy always cause re-render?

### ISSUE THREAD

**Issue by ulion** [dai-shi/react-tracked#99]
Modified from the first example: https://codesandbox.io/s/determined-euclid-xm0n5

As we can see, in the NotRealUse case, without any access to any property of the state, it always cause re-render.

Indeed we probably want it does not re-render in this case, since it is not really used?

Else I have to pretend to access the other property which is unnecessary at all.

**Comment by dai-shi** [comment]
Thanks for asking!

This has been asked several times and recently answered in the discord server: https://discord.gg/MrQdmzd

Please allow me to just copy&paste the answer in discord:

> This is by design. I know it may seem counter-intuitive. That happened to me too and the old version actually had changed the behavior intentionally. However, it's very weird implementation-wise. So, it's changed afterward. Now, the current behavior is intentional.
> 
> The rationale is to make the behavior consistent with child object.
> ```js
> const state = useTrackedState();
> // and doesn't touch the properties of state
> 
> const { obj } = useTrackedState();
> // and doesn't touch the properties of obj
> ```
> Both should trigger re-render if `state` or `obj` is changed, respectively.
> 
> In your use case, this is unavoidable. If this is troublesome, I wouldn't do like `useStore()`.
> If you are looking for a real hack, this may work.
> ```js
> const useStore = () => {
>   const state = useTrackedState();
>   state.SOME_NON_EXISTENT_PROPERTY; // a hack to touch a property
>   return {
>     state,
>     actions: useActions(),
>     libraries: useLibraries(),
>     // ...
>   };
> };
> ```

**Comment by dai-shi** [comment]
That seems correct. `meet_some_condition` is coming from props or useState, right? And, that branch is render, not in effect?
Would you try to repro it in codesandbox?

**Comment by ulion** [comment]
![image](https://user-images.githubusercontent.com/175133/120564495-9feb9e00-c43d-11eb-93a1-4dc1c669553a.png)
For now what I can see, is that, the re-render to all was run with old state value, as in the snapshot.
07:26:02 is the first render for multiple elements, all render goes into !meet_some_condition branch.
07:26:12 one of above element is re-rendered, with meet_some_condition === true, and accessed the composing property got value false
07:26:18.577 setState update the state with composing: true
07:26:18 (except the last line 18.590) all above elements got re-rendered, with old state value composing false probably (guessed by the 18.585 line)
07:26:18:590 the one element is re-rendered with new composing: true value.
With above info, do you have any idea what could cause all elements which useTracked there be rendered with old state value before re-render with new state value?

**Comment by dai-shi** [comment]
> With above info, do you have any idea what could cause all elements which useTracked there be rendered with old state value before re-render with new state value?

tbh, i'm not sure if i follow 100%.

if meet_some_condition from props changes, and it renders with old snapshot and then it re-renders with new one _without_ commits, it can be said it's expected behavior. (our old implementation pre v1.5 might have solved this with undocumented API, which we no longer use.)

Can you check with `useEffect(() => console.log(...))` to see if there's extra commits?

**Comment by ulion** [comment]
indeed, I added console.log to above https://codesandbox.io/s/distracted-taussig-cpctk?file=/src/index.js and it console like my snapshot, although the result UI does not change, but the code did run. So this is expected result? code always run but not change UI (commit?)?

**Comment by dai-shi** [comment]
wait, you are right... it's unexpected or my misunderstanding. let me see.

**Comment by dai-shi** [comment]
Oh, my. This is something I missed in #92.
`useTracked` is not taken care of, and our tests was all for CM.

https://codesandbox.io/s/morning-frog-yx5rg
This should work as you expect.

Let me fix this. This is really nice catch.

**Comment by ulion** [comment]
Great, just tried useTrackedState and it really works, no extra render occurs!

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-tracked/v/1.7.2

Thanks for your report!
